import {
  lucideArrowRight,
  lucideBookOpen,
  lucideBox,
  lucideChartColumn,
  lucideCheck,
  lucideChevronDown,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideDownload,
  lucideFile,
  lucideFileCheck,
  lucideFolder,
  lucideHistory,
  lucideInfo,
  lucideLanguages,
  lucideLoaderCircle,
  lucideMessagesSquare,
  lucidePencil,
  lucidePlay,
  lucidePlus,
  lucideRefreshCcw,
  lucideRefreshCw,
  lucideSave,
  lucideSend,
  lucideSettings,
  lucideSlidersHorizontal,
  lucideSparkles,
  lucideUpload,
  lucideUser,
  lucideWrench,
  lucideX,
  lucideZap,
} from '@ng-icons/lucide';

/** Every icon the app draws. */
export const APP_ICONS = {
  lucideArrowRight,
  lucideBookOpen,
  lucideBox,
  lucideChartColumn,
  lucideCheck,
  lucideChevronDown,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideDownload,
  lucideFile,
  lucideFileCheck,
  lucideFolder,
  lucideHistory,
  lucideInfo,
  lucideLanguages,
  lucideLoaderCircle,
  lucideMessagesSquare,
  lucidePencil,
  lucidePlay,
  lucidePlus,
  lucideRefreshCcw,
  lucideRefreshCw,
  lucideSave,
  lucideSend,
  lucideSettings,
  lucideSlidersHorizontal,
  lucideSparkles,
  lucideUpload,
  lucideUser,
  lucideWrench,
  lucideX,
  lucideZap,
};

export type AppIconName = keyof typeof APP_ICONS;
