from __future__ import annotations

import json
from typing import Any


HTTP_METHODS = {"delete", "get", "patch", "post"}
CLOSED_ENUM_SCHEMAS = frozenset(
    {
        "DocumentOperationPhase",
        "DocumentOperationStatus",
        "DraftGenerationJobStatus",
        "ManualDraftOperationStatus",
        "RuntimeInstallationStatus",
    }
)


def render_typescript(openapi: dict[str, Any]) -> str:
    """Render the generated Angular-side TypeScript client source."""
    schemas = openapi["components"]["schemas"]
    operations = collect_operations(openapi, schemas)
    lines = [
        "// Generated by apps/cert-prep-backend/scripts/generate_openapi_client.py.",
        "// Source of truth: FastAPI OpenAPI schema from cert_prep_backend.api.app:create_app().",
        "// Do not edit by hand.",
        "",
        "export interface Components {",
        "  schemas: {",
    ]
    for name in sorted(schemas):
        lines.append(f"    {name}: {render_component_schema_type(name, schemas)};")
    lines.extend(["  };", "}", ""])

    for alias in sorted(schemas):
        lines.append(f"export type {alias} = Components['schemas']['{alias}'];")
    lines.extend(
        [
            "",
            "export type CertPrepHttpMethod = 'DELETE' | 'GET' | 'PATCH' | 'POST';",
            "",
            "export interface CertPrepRequestOptions {",
            "  headers?: Readonly<Record<string, string>>;",
            "  signal?: AbortSignal;",
            "}",
            "",
            "export interface CertPrepHttpRequest {",
            "  method: CertPrepHttpMethod;",
            "  path: string;",
            "  body?: unknown;",
            "  headers?: Readonly<Record<string, string>>;",
            "  signal?: AbortSignal;",
            "}",
            "",
            "export interface CertPrepTransport {",
            "  request<TResponse>(request: CertPrepHttpRequest): Promise<TResponse>;",
            "}",
            "",
            "export interface CertPrepGeneratedClient {",
        ]
    )
    for operation in operations:
        lines.append(f"  {operation.signature()};")
    lines.extend(
        [
            "}",
            "",
            "export function createCertPrepGeneratedClient(",
            "  transport: CertPrepTransport,",
            "): CertPrepGeneratedClient {",
            "  return {",
        ]
    )
    for operation in operations:
        lines.extend(operation.factory_lines())
    lines.extend(["  };", "}", ""])
    return "\n".join(lines)


def collect_operations(
    openapi: dict[str, Any], schemas: dict[str, Any]
) -> list["ClientOperation"]:
    operations: list[ClientOperation] = []
    for path, path_item in openapi["paths"].items():
        for method, operation in path_item.items():
            if method not in HTTP_METHODS:
                continue
            operations.append(
                ClientOperation.from_openapi(
                    method=method,
                    path=path,
                    operation=operation,
                    schemas=schemas,
                )
            )
    return operations


def render_component_schema_type(name: str, schemas: dict[str, Any]) -> str:
    schema = schemas[name]
    enum_values = schema.get("enum")
    if name in CLOSED_ENUM_SCHEMAS and isinstance(enum_values, list) and enum_values:
        return " | ".join(json.dumps(value) for value in enum_values)
    return render_schema_type(schema, schemas)


def render_schema_type(schema: dict[str, Any], schemas: dict[str, Any]) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])

    if "anyOf" in schema:
        return render_union(schema["anyOf"], schemas)

    if "oneOf" in schema:
        return render_union(schema["oneOf"], schemas)

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return render_union([{"type": item} for item in schema_type], schemas)

    if schema_type == "object" or "properties" in schema:
        return render_object(schema, schemas)

    if schema_type == "array":
        items = schema.get("items", {})
        item_type = render_schema_type(items, schemas)
        if "|" in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"

    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "string":
        return "string"
    if schema_type == "null":
        return "null"

    return "unknown"


def render_object(schema: dict[str, Any], schemas: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    if not properties:
        return "Record<string, unknown>"

    fields = []
    for name, property_schema in properties.items():
        optional = "?" if name not in required else ""
        fields.append(
            f"{json.dumps(name)}{optional}: {render_schema_type(property_schema, schemas)}"
        )
    return "{ " + "; ".join(fields) + " }"


def render_union(items: list[dict[str, Any]], schemas: dict[str, Any]) -> str:
    rendered = []
    for item in items:
        value = render_schema_type(item, schemas)
        if value not in rendered:
            rendered.append(value)
    return " | ".join(rendered) if rendered else "unknown"


def ref_name(ref: str) -> str:
    name = ref.rsplit("/", 1)[-1]
    return f"Components['schemas']['{name}']"


class ClientOperation:
    """OpenAPI operation metadata needed to render one client method."""

    def __init__(
        self,
        *,
        name: str,
        method: str,
        path: str,
        parameters: list[str],
        request_type: str | None,
        request_required: bool,
        response_type: str,
    ) -> None:
        self.name = name
        self.method = method.upper()
        self.path = path
        self.parameters = parameters
        self.request_type = request_type
        self.request_required = request_required
        self.response_type = response_type

    @classmethod
    def from_openapi(
        cls,
        *,
        method: str,
        path: str,
        operation: dict[str, Any],
        schemas: dict[str, Any],
    ) -> "ClientOperation":
        return cls(
            name=operation_name(operation["operationId"], path, method),
            method=method,
            path=path,
            parameters=path_parameters(path),
            request_type=request_body_type(operation, schemas),
            request_required=bool(operation.get("requestBody", {}).get("required")),
            response_type=response_type(operation, schemas),
        )

    def signature(self) -> str:
        return f"{self.name}({self.arguments()}): Promise<{self.response_type}>"

    def factory_lines(self) -> list[str]:
        request_parts = [
            f"method: '{self.method}' as const",
            f"path: {self.path_expression()}",
        ]
        if self.request_type is not None:
            request_parts.append("body")
        request_parts.extend(
            [
                "...(options?.headers === undefined ? {} : { headers: options.headers })",
                "...(options?.signal === undefined ? {} : { signal: options.signal })",
            ]
        )
        return [
            f"    {self.name}: ({self.arguments()}) =>",
            f"      transport.request<{self.response_type}>({{ {', '.join(request_parts)} }}),",
        ]

    def arguments(self) -> str:
        arguments = [f"{to_camel(parameter)}: string" for parameter in self.parameters]
        if self.request_type is not None:
            optional = "" if self.request_required else "?"
            arguments.append(f"body{optional}: {self.request_type}")
        arguments.append("options?: CertPrepRequestOptions")
        return ", ".join(arguments)

    def path_expression(self) -> str:
        if not self.parameters:
            return json.dumps(self.path)

        expression = self.path
        for parameter in self.parameters:
            expression = expression.replace(
                f"{{{parameter}}}",
                f"${{encodeURIComponent({to_camel(parameter)})}}",
            )
        return f"`{expression}`"


def operation_name(operation_id: str, path: str, method: str) -> str:
    suffix = f"_{sanitize_path(path)}_{method}"
    raw_name = operation_id
    if operation_id.endswith(suffix):
        raw_name = operation_id[: -len(suffix)]
    elif operation_id.endswith(f"_{method}"):
        raw_name = operation_id[: -(len(method) + 1)]
    return to_camel(raw_name)


def sanitize_path(path: str) -> str:
    sanitized = path.strip("/").replace("/", "_")
    return sanitized.replace("{", "_").replace("}", "_").replace("-", "_")


def path_parameters(path: str) -> list[str]:
    parameters: list[str] = []
    current = ""
    in_parameter = False
    for character in path:
        if character == "{":
            in_parameter = True
            current = ""
        elif character == "}" and in_parameter:
            parameters.append(current)
            in_parameter = False
        elif in_parameter:
            current += character
    return parameters


def request_body_type(operation: dict[str, Any], schemas: dict[str, Any]) -> str | None:
    request_body = operation.get("requestBody")
    if request_body is None:
        return None

    content = request_body.get("content", {})
    if "multipart/form-data" in content:
        return "FormData"
    json_schema = content.get("application/json", {}).get("schema")
    if json_schema is not None:
        return render_schema_type(json_schema, schemas)
    return "unknown"


def response_type(operation: dict[str, Any], schemas: dict[str, Any]) -> str:
    responses = operation.get("responses", {})
    for status_code in sorted(responses):
        if not status_code.startswith("2"):
            continue
        response = responses[status_code]
        json_schema = response.get("content", {}).get("application/json", {}).get("schema")
        if json_schema is not None:
            return render_schema_type(json_schema, schemas)
        return "void"
    return "unknown"


def to_camel(value: str) -> str:
    head, *tail = value.split("_")
    return head + "".join(part.capitalize() for part in tail)
