from __future__ import annotations

import sys

from ocr_windowsml_prepare import (
    BACKEND_ROOT,
    CONVERTERS,
    CONVERSION_TIMEOUT_SECONDS,
    DEFAULT_MODEL_DIR,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_SOURCES_DIR,
    DOCKER_PADDLEX_IMAGE,
    SCRIPT_DIR,
    SOURCE_ARTIFACTS,
    ConversionResult,
    ConverterRunner,
    DownloadFn,
    SourceArtifact,
    build_pipeline_contract,
    build_report,
    classify_conversion_blocker,
    classify_prepare_status,
    conversion_report,
    converter_runner_for,
    default_output_path,
    docker_work_path,
    download_file,
    ensure_source_artifact,
    extract_character_dict,
    extract_source_artifact,
    inspect_conversion_tool,
    inspect_prepared_model_artifacts,
    load_inference_yml,
    main,
    model_file_state,
    normalize_converter,
    parse_args,
    prepare_metadata_artifacts,
    prepare_onnx_artifacts,
    recommended_next_step,
    run_docker_paddlex_conversion,
    run_paddlex_conversion,
    safe_extract_tar,
    sanitized_rec_postprocess,
    sha256_file,
    source_artifact_report,
    verify_source_archive,
)


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


__all__ = [
    "BACKEND_ROOT",
    "CONVERTERS",
    "CONVERSION_TIMEOUT_SECONDS",
    "ConverterRunner",
    "ConversionResult",
    "DEFAULT_MODEL_DIR",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_SOURCES_DIR",
    "DOCKER_PADDLEX_IMAGE",
    "DownloadFn",
    "SCRIPT_DIR",
    "SOURCE_ARTIFACTS",
    "SourceArtifact",
    "build_pipeline_contract",
    "build_report",
    "classify_conversion_blocker",
    "classify_prepare_status",
    "conversion_report",
    "converter_runner_for",
    "default_output_path",
    "docker_work_path",
    "download_file",
    "ensure_source_artifact",
    "extract_character_dict",
    "extract_source_artifact",
    "inspect_conversion_tool",
    "inspect_prepared_model_artifacts",
    "load_inference_yml",
    "main",
    "model_file_state",
    "normalize_converter",
    "parse_args",
    "prepare_metadata_artifacts",
    "prepare_onnx_artifacts",
    "recommended_next_step",
    "run_docker_paddlex_conversion",
    "run_paddlex_conversion",
    "safe_extract_tar",
    "sanitized_rec_postprocess",
    "sha256_file",
    "source_artifact_report",
    "verify_source_archive",
]


if __name__ == "__main__":
    main()
