// Generated by apps/cert-prep-backend/scripts/generate_openapi_client.py.
// Source of truth: FastAPI OpenAPI schema from cert_prep_backend.api.app:create_app().
// Do not edit by hand.

export interface Components {
  schemas: {
    AnswerKeySource: string;
    ApiErrorRead: { "code": string; "message": string; "details"?: Record<string, unknown> | null };
    Body_upload_document_projects__project_id__documents_post: { "file": string; "language_hint"?: string };
    ChunkList: { "items": Components['schemas']['ChunkRead'][] };
    ChunkRead: { "id": string; "document_id": string; "page_number": number; "chunk_index": number; "text": string; "raw_text": string; "line_start": number | null; "line_end": number | null; "line_count": number; "source_excerpt": string; "extraction_method": Components['schemas']['PdfExtractionMethod'] | string; "content_profile": Components['schemas']['ContentProfile'] | string; "created_at": string };
    ContentProfile: string;
    DocumentList: { "items": Components['schemas']['DocumentRead'][] };
    DocumentOperationPhase: "uploading" | "processing" | "canceling" | "committing" | "canceled" | "completed" | "failed";
    DocumentOperationRead: { "id": string; "project_id": string; "document_id": string | null; "status": Components['schemas']['DocumentOperationStatus']; "phase": Components['schemas']['DocumentOperationPhase']; "cancellable": boolean; "error": string | null; "created_at": string; "updated_at": string };
    DocumentOperationStatus: "queued" | "running" | "cancel_requested" | "canceled" | "succeeded" | "failed";
    DocumentRead: { "id": string; "project_id": string; "filename": string; "sha256": string; "language_hint": string; "page_count": number; "has_text": boolean; "status": Components['schemas']['SourceDocumentStatus'] | string; "extraction_method": Components['schemas']['PdfExtractionMethod'] | string; "ocr_device": string | null; "ocr_fallback_reason": string | null; "ocr_duration_ms": number; "processed_page_count": number; "parse_wall_duration_ms": number; "render_duration_ms": number; "ocr_engine_duration_ms": number; "ocr_worker_count": number; "first_chunk_ms": number; "exam_item_count": number; "content_profile": Components['schemas']['ContentProfile'] | string; "classification_detail": string; "chunks_count": number; "created_at": string; "updated_at": string };
    DraftGenerateRequest: { "limit"?: number; "strategy"?: Components['schemas']['DraftGenerationStrategy'] };
    DraftGenerationJobList: { "items": Components['schemas']['DraftGenerationJobRead'][] };
    DraftGenerationJobRead: { "id": string; "project_id": string; "document_id": string; "chunk_id": string; "page_number": number; "strategy": Components['schemas']['DraftGenerationStrategy']; "status": Components['schemas']['DraftGenerationJobStatus']; "phase": string; "cancellable": boolean; "provider": string; "model": string; "effective_provider": string | null; "effective_model": string | null; "fallback_reason": string | null; "generated_count": number; "retry_count": number; "last_error": string | null; "created_at": string; "updated_at": string };
    DraftGenerationJobStatus: "pending" | "running" | "cancel_requested" | "canceled" | "succeeded" | "skipped_provider_unavailable" | "skipped_missing_model" | "failed";
    DraftGenerationStrategy: string;
    DraftStatus: string;
    HTTPValidationError: { "detail"?: Components['schemas']['ValidationError'][] };
    HealthResponse: { "status": string; "app": string; "version": string; "python_version": string; "runtime_mode": string };
    LLMExecutionMode: string;
    LLMHealthRead: { "provider": string; "model": string; "available": boolean; "detail": string; "unavailable_reason"?: string | null; "configured_model"?: string | null; "effective_model"?: string | null; "fallback_models"?: string[]; "fallback_reason"?: string | null; "execution_mode"?: Components['schemas']['LLMExecutionMode'] | null; "execution_warning"?: string | null; "profile_id"?: string | null; "base_model"?: string | null; "modelfile_sha256"?: string | null; "profile_reason"?: string | null; "profile_warnings"?: string[] };
    LLMProviderName: string;
    LLMProviderPreference: string;
    LLMProviderSelectionRead: { "preference": Components['schemas']['LLMProviderPreference']; "selected_provider": Components['schemas']['LLMProviderName']; "effective_provider": Components['schemas']['LLMProviderName']; "configured_model": string; "effective_model": string; "selection_reason": string; "fallback_reason"?: string | null; "runtime_requirement_kind"?: Components['schemas']['RuntimeRequirementKind'] | null; "model_requirement_kind"?: Components['schemas']['RuntimeRequirementKind'] | null };
    MachineAcceleratorRead: { "kind": string; "name": string; "vendor"?: string | null; "memory_bytes"?: number | null; "driver_version"?: string | null; "device_id"?: string | null };
    MachineCpuRead: { "architecture": string; "name"?: string | null; "physical_cores"?: number | null; "logical_cores"?: number | null };
    MachineInventoryRead: { "platform": string; "platform_version": string; "architecture": string; "cpu": Components['schemas']['MachineCpuRead']; "ram": Components['schemas']['MachineRamRead']; "storage": Components['schemas']['MachineStorageRead']; "accelerators"?: Components['schemas']['MachineAcceleratorRead'][]; "warnings"?: string[]; "schema_version"?: number };
    MachineRamRead: { "total_bytes"?: number | null; "available_bytes"?: number | null };
    MachineStorageRead: { "path": string; "free_bytes"?: number | null; "total_bytes"?: number | null };
    ManualDraftGenerationOperationRead: { "id": string; "project_id": string; "document_id": string; "limit": number; "strategy": Components['schemas']['DraftGenerationStrategy']; "status": Components['schemas']['ManualDraftOperationStatus']; "phase": string; "cancellable": boolean; "provider": string; "model": string; "effective_provider"?: string | null; "effective_model"?: string | null; "fallback_reason"?: string | null; "generated_count": number; "error"?: string | null; "created_at": string; "updated_at": string; "commit_started_at"?: string | null };
    ManualDraftOperationStatus: "queued" | "running" | "cancel_requested" | "canceled" | "succeeded" | "failed";
    ModelDownloadRead: { "id": string; "provider": string; "model": string; "status": Components['schemas']['RuntimeInstallationStatus']; "phase": string; "cancellable": boolean; "detail": string; "completed": number | null; "total": number | null; "created_at": string; "updated_at": string; "commit_started_at"?: string | null; "error"?: string | null };
    OCRHealthRead: { "provider": string; "engine": string; "available": boolean; "detail": string; "python_version": string; "paddle_version": string | null; "paddleocr_version": string | null; "selected_device": string | null; "cuda_available": boolean; "gpu_count": number; "model_cache_dir": string | null; "fallback_reason": string | null; "unavailable_reason"?: string | null };
    OllamaModelProfileRead: { "profile_id": string; "display_name": string; "description": string; "base_model": string; "local_model": string; "context_window": number; "system_prompt": string; "parameters"?: Record<string, unknown>; "min_total_ram_bytes"?: number | null; "min_available_ram_bytes"?: number | null; "min_free_disk_bytes"?: number | null; "min_vram_bytes"?: number | null; "auto_selectable": boolean; "explicit_opt_in_required": boolean; "fallback_profile_ids"?: string[] };
    OllamaProfileSelectionRead: { "profile_enabled": boolean; "profile_id"?: string | null; "selected_profile"?: Components['schemas']['OllamaModelProfileRead'] | null; "support_status": string; "reason": string; "fallback_profiles"?: Components['schemas']['OllamaModelProfileRead'][]; "fallback_models"?: string[]; "warnings"?: string[]; "inventory"?: Components['schemas']['MachineInventoryRead'] | null; "modelfile_sha256"?: string | null; "effective_model": string; "base_model"?: string | null };
    OllamaProfilesRead: { "items": Components['schemas']['OllamaModelProfileRead'][] };
    PdfExtractionMethod: string;
    PracticeAttemptCreate: { "question_id": string; "selected_answer": string };
    PracticeAttemptRead: { "id": string; "session_id": string; "project_id": string; "question_id": string; "selected_answer": string; "is_correct": boolean; "created_at": string };
    PracticeSessionCreate: { "mode"?: Components['schemas']['PracticeSessionMode']; "document_id"?: string | null; "question_count"?: number | null; "random_seed"?: number | null; "wrong_attempt_ids"?: string[] | null };
    PracticeSessionList: { "items": Components['schemas']['PracticeSessionSummaryRead'][] };
    PracticeSessionMode: string;
    PracticeSessionQuestionRead: { "id": string; "question": string; "choices": string[]; "answer": string | null; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null; "document_id": string | null };
    PracticeSessionRead: { "id": string; "project_id": string; "question_ids": string[]; "questions": Components['schemas']['PracticeSessionQuestionRead'][]; "mode": Components['schemas']['PracticeSessionMode']; "document_id": string | null; "question_count": number; "random_seed": number | null; "status": Components['schemas']['PracticeSessionStatus']; "created_at": string; "completed_at": string | null; "abandoned_at": string | null; "attempts": Components['schemas']['PracticeAttemptRead'][] };
    PracticeSessionStatus: string;
    PracticeSessionSummaryRead: { "id": string; "project_id": string; "mode": Components['schemas']['PracticeSessionMode']; "document_id": string | null; "status": Components['schemas']['PracticeSessionStatus']; "created_at": string };
    ProjectCreate: { "name": string; "description"?: string };
    ProjectList: { "items": Components['schemas']['ProjectRead'][] };
    ProjectRead: { "id": string; "name": string; "description": string; "created_at": string; "updated_at": string };
    ProjectUpdate: { "name"?: string | null; "description"?: string | null };
    QuestionDraftCreate: { "question"?: string; "choices"?: string[]; "answer"?: string | null; "answer_key_source"?: Components['schemas']['AnswerKeySource'] | string; "rationale"?: string | null; "citation_page"?: number | null; "source_excerpt"?: string | null; "confidence"?: number | null; "document_id"?: string | null; "chunk_id"?: string | null; "source_order"?: number | null; "source_question_number"?: string | null; "item_kind"?: Components['schemas']['QuestionItemKind'] | string; "group_key"?: string | null; "group_prompt"?: string | null };
    QuestionDraftList: { "items": Components['schemas']['QuestionDraftRead'][] };
    QuestionDraftRead: { "id": string; "project_id": string; "document_id": string | null; "chunk_id": string | null; "question": string; "choices": string[]; "answer": string | null; "answer_key_source": Components['schemas']['AnswerKeySource'] | string; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null; "confidence": number | null; "source_order": number | null; "source_question_number": string | null; "item_kind": Components['schemas']['QuestionItemKind'] | string; "group_key": string | null; "group_prompt": string | null; "status": Components['schemas']['DraftStatus'] | string; "rejection_reason": string | null; "created_at": string; "updated_at": string };
    QuestionDraftUpdate: { "question"?: string | null; "choices"?: string[] | null; "answer"?: string | null; "answer_key_source"?: Components['schemas']['AnswerKeySource'] | string | null; "rationale"?: string | null; "citation_page"?: number | null; "source_excerpt"?: string | null; "confidence"?: number | null; "source_order"?: number | null; "source_question_number"?: string | null; "item_kind"?: Components['schemas']['QuestionItemKind'] | string | null; "group_key"?: string | null; "group_prompt"?: string | null };
    QuestionItemKind: string;
    RuntimeInstallationRead: { "id": string; "kind": Components['schemas']['RuntimeRequirementKind']; "provider": string; "model": string; "status": Components['schemas']['RuntimeInstallationStatus']; "phase": string; "cancellable": boolean; "detail": string; "completed": number | null; "total": number | null; "created_at": string; "updated_at": string; "commit_started_at"?: string | null; "error"?: string | null };
    RuntimeInstallationStatus: "queued" | "running" | "cancel_requested" | "canceled" | "waiting_for_user" | "succeeded" | "failed";
    RuntimeRequirementKind: string;
    RuntimeRequirementRead: { "kind": Components['schemas']['RuntimeRequirementKind']; "label": string; "available": boolean; "detail": string; "unavailable_reason": string | null; "version"?: string | null; "bytes"?: number | null; "installed_path"?: string | null };
    RuntimeRequirementsRead: { "items": Components['schemas']['RuntimeRequirementRead'][] };
    SourceDocumentStatus: string;
    ValidationError: { "loc": (string | number)[]; "msg": string; "type": string; "input"?: unknown; "ctx"?: Record<string, unknown> };
    WrongAnswerClusterRead: { "document_id": string | null; "citation_page": number | null; "current_wrong_count": number; "cleared_count": number; "last_wrong_at": string | null };
    WrongAnswerExplanationRead: { "attempt_id": string; "explanation": string; "provider": string; "model": string; "grounded_fields": Components['schemas']['WrongAnswerGroundedFields']; "fallback": boolean };
    WrongAnswerGroundedFields: { "question": string; "selected_answer": string; "correct_answer": string | null; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null };
    WrongAnswerList: { "items": Components['schemas']['WrongAnswerRead'][] };
    WrongAnswerRead: { "attempt_id": string; "session_id": string; "question_id": string; "question": string; "selected_answer": string; "correct_answer": string | null; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null; "document_id": string | null; "created_at": string };
    WrongAnswerRepeatedMissRead: { "question_id": string; "question": string; "document_id": string | null; "citation_page": number | null; "source_excerpt": string | null; "miss_count": number; "last_wrong_at": string };
    WrongAnswerSummaryRead: { "current_wrong_count": number; "cleared_count": number; "last_wrong_date": string | null; "repeated_misses": Components['schemas']['WrongAnswerRepeatedMissRead'][]; "clusters": Components['schemas']['WrongAnswerClusterRead'][] };
  };
}

export type AnswerKeySource = Components['schemas']['AnswerKeySource'];
export type ApiErrorRead = Components['schemas']['ApiErrorRead'];
export type Body_upload_document_projects__project_id__documents_post = Components['schemas']['Body_upload_document_projects__project_id__documents_post'];
export type ChunkList = Components['schemas']['ChunkList'];
export type ChunkRead = Components['schemas']['ChunkRead'];
export type ContentProfile = Components['schemas']['ContentProfile'];
export type DocumentList = Components['schemas']['DocumentList'];
export type DocumentOperationPhase = Components['schemas']['DocumentOperationPhase'];
export type DocumentOperationRead = Components['schemas']['DocumentOperationRead'];
export type DocumentOperationStatus = Components['schemas']['DocumentOperationStatus'];
export type DocumentRead = Components['schemas']['DocumentRead'];
export type DraftGenerateRequest = Components['schemas']['DraftGenerateRequest'];
export type DraftGenerationJobList = Components['schemas']['DraftGenerationJobList'];
export type DraftGenerationJobRead = Components['schemas']['DraftGenerationJobRead'];
export type DraftGenerationJobStatus = Components['schemas']['DraftGenerationJobStatus'];
export type DraftGenerationStrategy = Components['schemas']['DraftGenerationStrategy'];
export type DraftStatus = Components['schemas']['DraftStatus'];
export type HTTPValidationError = Components['schemas']['HTTPValidationError'];
export type HealthResponse = Components['schemas']['HealthResponse'];
export type LLMExecutionMode = Components['schemas']['LLMExecutionMode'];
export type LLMHealthRead = Components['schemas']['LLMHealthRead'];
export type LLMProviderName = Components['schemas']['LLMProviderName'];
export type LLMProviderPreference = Components['schemas']['LLMProviderPreference'];
export type LLMProviderSelectionRead = Components['schemas']['LLMProviderSelectionRead'];
export type MachineAcceleratorRead = Components['schemas']['MachineAcceleratorRead'];
export type MachineCpuRead = Components['schemas']['MachineCpuRead'];
export type MachineInventoryRead = Components['schemas']['MachineInventoryRead'];
export type MachineRamRead = Components['schemas']['MachineRamRead'];
export type MachineStorageRead = Components['schemas']['MachineStorageRead'];
export type ManualDraftGenerationOperationRead = Components['schemas']['ManualDraftGenerationOperationRead'];
export type ManualDraftOperationStatus = Components['schemas']['ManualDraftOperationStatus'];
export type ModelDownloadRead = Components['schemas']['ModelDownloadRead'];
export type OCRHealthRead = Components['schemas']['OCRHealthRead'];
export type OllamaModelProfileRead = Components['schemas']['OllamaModelProfileRead'];
export type OllamaProfileSelectionRead = Components['schemas']['OllamaProfileSelectionRead'];
export type OllamaProfilesRead = Components['schemas']['OllamaProfilesRead'];
export type PdfExtractionMethod = Components['schemas']['PdfExtractionMethod'];
export type PracticeAttemptCreate = Components['schemas']['PracticeAttemptCreate'];
export type PracticeAttemptRead = Components['schemas']['PracticeAttemptRead'];
export type PracticeSessionCreate = Components['schemas']['PracticeSessionCreate'];
export type PracticeSessionList = Components['schemas']['PracticeSessionList'];
export type PracticeSessionMode = Components['schemas']['PracticeSessionMode'];
export type PracticeSessionQuestionRead = Components['schemas']['PracticeSessionQuestionRead'];
export type PracticeSessionRead = Components['schemas']['PracticeSessionRead'];
export type PracticeSessionStatus = Components['schemas']['PracticeSessionStatus'];
export type PracticeSessionSummaryRead = Components['schemas']['PracticeSessionSummaryRead'];
export type ProjectCreate = Components['schemas']['ProjectCreate'];
export type ProjectList = Components['schemas']['ProjectList'];
export type ProjectRead = Components['schemas']['ProjectRead'];
export type ProjectUpdate = Components['schemas']['ProjectUpdate'];
export type QuestionDraftCreate = Components['schemas']['QuestionDraftCreate'];
export type QuestionDraftList = Components['schemas']['QuestionDraftList'];
export type QuestionDraftRead = Components['schemas']['QuestionDraftRead'];
export type QuestionDraftUpdate = Components['schemas']['QuestionDraftUpdate'];
export type QuestionItemKind = Components['schemas']['QuestionItemKind'];
export type RuntimeInstallationRead = Components['schemas']['RuntimeInstallationRead'];
export type RuntimeInstallationStatus = Components['schemas']['RuntimeInstallationStatus'];
export type RuntimeRequirementKind = Components['schemas']['RuntimeRequirementKind'];
export type RuntimeRequirementRead = Components['schemas']['RuntimeRequirementRead'];
export type RuntimeRequirementsRead = Components['schemas']['RuntimeRequirementsRead'];
export type SourceDocumentStatus = Components['schemas']['SourceDocumentStatus'];
export type ValidationError = Components['schemas']['ValidationError'];
export type WrongAnswerClusterRead = Components['schemas']['WrongAnswerClusterRead'];
export type WrongAnswerExplanationRead = Components['schemas']['WrongAnswerExplanationRead'];
export type WrongAnswerGroundedFields = Components['schemas']['WrongAnswerGroundedFields'];
export type WrongAnswerList = Components['schemas']['WrongAnswerList'];
export type WrongAnswerRead = Components['schemas']['WrongAnswerRead'];
export type WrongAnswerRepeatedMissRead = Components['schemas']['WrongAnswerRepeatedMissRead'];
export type WrongAnswerSummaryRead = Components['schemas']['WrongAnswerSummaryRead'];

export type CertPrepHttpMethod = 'DELETE' | 'GET' | 'PATCH' | 'POST';

export interface CertPrepRequestOptions {
  headers?: Readonly<Record<string, string>>;
  signal?: AbortSignal;
}

export interface CertPrepHttpRequest {
  method: CertPrepHttpMethod;
  path: string;
  body?: unknown;
  headers?: Readonly<Record<string, string>>;
  signal?: AbortSignal;
}

export interface CertPrepTransport {
  request<TResponse>(request: CertPrepHttpRequest): Promise<TResponse>;
}

export interface CertPrepGeneratedClient {
  health(options?: CertPrepRequestOptions): Promise<Components['schemas']['HealthResponse']>;
  listProjects(options?: CertPrepRequestOptions): Promise<Components['schemas']['ProjectList']>;
  createProject(body: Components['schemas']['ProjectCreate'], options?: CertPrepRequestOptions): Promise<Components['schemas']['ProjectRead']>;
  getProject(projectId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['ProjectRead']>;
  updateProject(projectId: string, body: Components['schemas']['ProjectUpdate'], options?: CertPrepRequestOptions): Promise<Components['schemas']['ProjectRead']>;
  deleteProject(projectId: string, options?: CertPrepRequestOptions): Promise<void>;
  listDocuments(projectId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['DocumentList']>;
  uploadDocument(projectId: string, body: FormData, options?: CertPrepRequestOptions): Promise<Components['schemas']['DocumentRead']>;
  getDocument(projectId: string, documentId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['DocumentRead']>;
  cancelDocumentProcessing(projectId: string, documentId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['DocumentOperationRead']>;
  retryDocumentProcessing(projectId: string, documentId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['DocumentOperationRead']>;
  listDocumentChunks(projectId: string, documentId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['ChunkList']>;
  getDocumentOperation(projectId: string, operationId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['DocumentOperationRead']>;
  cancelDocumentOperation(projectId: string, operationId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['DocumentOperationRead']>;
  generateDocumentDrafts(projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions): Promise<Components['schemas']['QuestionDraftList']>;
  listDocumentDraftJobs(projectId: string, documentId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['DraftGenerationJobList']>;
  retryDocumentDraftJobs(projectId: string, documentId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['DraftGenerationJobList']>;
  cancelDocumentDraftJob(projectId: string, documentId: string, jobId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['DraftGenerationJobRead']>;
  startManualDraftOperation(projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions): Promise<Components['schemas']['ManualDraftGenerationOperationRead']>;
  getManualDraftOperation(projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['ManualDraftGenerationOperationRead']>;
  cancelManualDraftOperation(projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['ManualDraftGenerationOperationRead']>;
  createQuestionDraft(projectId: string, body: Components['schemas']['QuestionDraftCreate'], options?: CertPrepRequestOptions): Promise<Components['schemas']['QuestionDraftRead']>;
  listQuestionDrafts(projectId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['QuestionDraftList']>;
  updateQuestionDraft(projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate'], options?: CertPrepRequestOptions): Promise<Components['schemas']['QuestionDraftRead']>;
  createPracticeSession(projectId: string, body: Components['schemas']['PracticeSessionCreate'], options?: CertPrepRequestOptions): Promise<Components['schemas']['PracticeSessionRead']>;
  listActivePracticeSessions(projectId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['PracticeSessionList']>;
  getPracticeSession(projectId: string, sessionId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['PracticeSessionRead']>;
  abandonPracticeSession(projectId: string, sessionId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['PracticeSessionRead']>;
  recordPracticeAttempt(projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate'], options?: CertPrepRequestOptions): Promise<Components['schemas']['PracticeAttemptRead']>;
  listWrongAnswers(projectId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['WrongAnswerList']>;
  summarizeWrongAnswers(projectId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['WrongAnswerSummaryRead']>;
  explainWrongAnswer(projectId: string, attemptId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['WrongAnswerExplanationRead']>;
  llmHealth(options?: CertPrepRequestOptions): Promise<Components['schemas']['LLMHealthRead']>;
  llmProviderSelection(options?: CertPrepRequestOptions): Promise<Components['schemas']['LLMProviderSelectionRead']>;
  llmProfiles(options?: CertPrepRequestOptions): Promise<Components['schemas']['OllamaProfilesRead']>;
  llmProfileSelection(options?: CertPrepRequestOptions): Promise<Components['schemas']['OllamaProfileSelectionRead']>;
  startModelDownload(options?: CertPrepRequestOptions): Promise<Components['schemas']['ModelDownloadRead']>;
  getModelDownload(jobId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['ModelDownloadRead']>;
  cancelModelDownload(jobId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['ModelDownloadRead']>;
  ocrHealth(options?: CertPrepRequestOptions): Promise<Components['schemas']['OCRHealthRead']>;
  runtimeRequirements(options?: CertPrepRequestOptions): Promise<Components['schemas']['RuntimeRequirementsRead']>;
  machineInventory(options?: CertPrepRequestOptions): Promise<Components['schemas']['MachineInventoryRead']>;
  startRuntimeInstallation(kind: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['RuntimeInstallationRead']>;
  getRuntimeInstallation(jobId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['RuntimeInstallationRead']>;
  cancelRuntimeInstallation(jobId: string, options?: CertPrepRequestOptions): Promise<Components['schemas']['RuntimeInstallationRead']>;
}

export function createCertPrepGeneratedClient(
  transport: CertPrepTransport,
): CertPrepGeneratedClient {
  return {
    health: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['HealthResponse']>({ method: 'GET' as const, path: "/health", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    listProjects: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ProjectList']>({ method: 'GET' as const, path: "/projects", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    createProject: (body: Components['schemas']['ProjectCreate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ProjectRead']>({ method: 'POST' as const, path: "/projects", body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    getProject: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ProjectRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    updateProject: (projectId: string, body: Components['schemas']['ProjectUpdate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ProjectRead']>({ method: 'PATCH' as const, path: `/projects/${encodeURIComponent(projectId)}`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    deleteProject: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<void>({ method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    listDocuments: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    uploadDocument: (projectId: string, body: FormData, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    getDocument: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    cancelDocumentProcessing: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentOperationRead']>({ method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/processing`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    retryDocumentProcessing: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentOperationRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/retry`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    listDocumentChunks: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ChunkList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/chunks`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    getDocumentOperation: (projectId: string, operationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentOperationRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/document-operations/${encodeURIComponent(operationId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    cancelDocumentOperation: (projectId: string, operationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentOperationRead']>({ method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}/document-operations/${encodeURIComponent(operationId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    generateDocumentDrafts: (projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['QuestionDraftList']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/drafts`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    listDocumentDraftJobs: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DraftGenerationJobList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-jobs`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    retryDocumentDraftJobs: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DraftGenerationJobList']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-jobs/retry`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    cancelDocumentDraftJob: (projectId: string, documentId: string, jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DraftGenerationJobRead']>({ method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-jobs/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    startManualDraftOperation: (projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ManualDraftGenerationOperationRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-operations`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    getManualDraftOperation: (projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ManualDraftGenerationOperationRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-operations/${encodeURIComponent(operationId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    cancelManualDraftOperation: (projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ManualDraftGenerationOperationRead']>({ method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-operations/${encodeURIComponent(operationId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    createQuestionDraft: (projectId: string, body: Components['schemas']['QuestionDraftCreate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['QuestionDraftRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    listQuestionDrafts: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['QuestionDraftList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    updateQuestionDraft: (projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['QuestionDraftRead']>({ method: 'PATCH' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts/${encodeURIComponent(draftId)}`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    createPracticeSession: (projectId: string, body: Components['schemas']['PracticeSessionCreate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeSessionRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    listActivePracticeSessions: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeSessionList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    getPracticeSession: (projectId: string, sessionId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeSessionRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    abandonPracticeSession: (projectId: string, sessionId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeSessionRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}/abandon`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    recordPracticeAttempt: (projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeAttemptRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}/attempts`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    listWrongAnswers: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['WrongAnswerList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/wrong-answers`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    summarizeWrongAnswers: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['WrongAnswerSummaryRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/wrong-answers/summary`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    explainWrongAnswer: (projectId: string, attemptId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['WrongAnswerExplanationRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/wrong-answers/${encodeURIComponent(attemptId)}/explanation`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    llmHealth: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['LLMHealthRead']>({ method: 'GET' as const, path: "/llm/health", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    llmProviderSelection: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['LLMProviderSelectionRead']>({ method: 'GET' as const, path: "/llm/provider-selection", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    llmProfiles: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['OllamaProfilesRead']>({ method: 'GET' as const, path: "/llm/profiles", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    llmProfileSelection: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['OllamaProfileSelectionRead']>({ method: 'GET' as const, path: "/llm/profile-selection", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    startModelDownload: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ModelDownloadRead']>({ method: 'POST' as const, path: "/llm/model-downloads", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    getModelDownload: (jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ModelDownloadRead']>({ method: 'GET' as const, path: `/llm/model-downloads/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    cancelModelDownload: (jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ModelDownloadRead']>({ method: 'DELETE' as const, path: `/llm/model-downloads/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    ocrHealth: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['OCRHealthRead']>({ method: 'GET' as const, path: "/ocr/health", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    runtimeRequirements: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeRequirementsRead']>({ method: 'GET' as const, path: "/runtime/requirements", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    machineInventory: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['MachineInventoryRead']>({ method: 'GET' as const, path: "/runtime/machine-inventory", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    startRuntimeInstallation: (kind: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallationRead']>({ method: 'POST' as const, path: `/runtime/installations/${encodeURIComponent(kind)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    getRuntimeInstallation: (jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallationRead']>({ method: 'GET' as const, path: `/runtime/installations/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
    cancelRuntimeInstallation: (jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallationRead']>({ method: 'DELETE' as const, path: `/runtime/installations/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) }),
  };
}
