// Generated by apps/cert-prep-backend/scripts/generate_openapi_client.py.
// Source of truth: FastAPI OpenAPI schema from cert_prep_backend.api.app:create_app().
// Do not edit by hand.

import type { Observable } from 'rxjs';

export interface Components {
  schemas: {
    AnswerKeySource: string;
    ApiErrorRead: { "code": string; "message": string; "details"?: Record<string, unknown> | null };
    Body_create_capture_projects__project_id__capture_workbench_captures_post: { "file": string };
    Body_upload_document_projects__project_id__documents_post: { "file": string; "language_hint"?: string };
    CaptureBlock: { "blockId": string; "order": number; "type": string; "sourceSegmentId": string; "locator": Components['schemas']['PageLocator'] | Components['schemas']['TimeLocator']; "sourceText": string; "targetText": string };
    CaptureDocument: { "schemaVersion"?: string; "source": Components['schemas']['CaptureSource']; "rawSegments": Components['schemas']['RawCaptureSegment'][]; "blocks": Components['schemas']['CaptureBlock'][]; "sourceText": string; "targetText": string; "extractionEngine": Components['schemas']['CaptureEngine']; "structuringEngine": Components['schemas']['CaptureEngine']; "warnings"?: string[]; "createdAt": string; "completedAt": string };
    CaptureEngine: { "engine": string; "model": string; "digest": string; "device"?: string | null };
    CaptureFailureV2: { "code": string; "message": string; "stage"?: string | null; "retryable"?: boolean };
    CaptureReview: { "reviewVersion"?: number; "edits"?: Components['schemas']['CaptureReviewEdit'][] };
    CaptureReviewEdit: { "segmentId": string; "reviewedText": string };
    CaptureReviewOperationRead: { "protocolVersion"?: string; "captureId": string; "ingestionId": string; "kind"?: Components['schemas']['CaptureSourceKind']; "status": Components['schemas']['StreamingCaptureStatus']; "progress"?: number | null; "partialRevision": number; "lastEventSequence": number; "source"?: Components['schemas']['CaptureSource'] | null; "error"?: Components['schemas']['CaptureFailureV2'] | null; "createdAt": string; "updatedAt": string; "completedAt"?: string | null; "documentId": string };
    CaptureReviewStructureRequest: { "clientRequestId": string; "review": Components['schemas']['CaptureReview'] };
    CaptureSource: { "sha256": string; "fileName": string; "mediaType": string; "bytes": number };
    CaptureSourceKind: string;
    CaptureStreamingCommitRequest: { "clientRequestId": string; "candidate": Components['schemas']['CaptureDocument'] };
    CaptureStreamingFailureRequest: { "clientRequestId"?: string | null; "code": string; "message": string };
    CaptureStreamingResultRead: { "operation": Components['schemas']['CaptureReviewOperationRead']; "raw": Components['schemas']['RawCapture']; "result": Components['schemas']['CaptureDocument'] };
    ChunkList: { "items": Components['schemas']['ChunkRead'][] };
    ChunkRead: { "id": string; "document_id": string; "page_number": number; "chunk_index": number; "text": string; "raw_text": string; "line_start": number | null; "line_end": number | null; "line_count": number; "source_excerpt": string; "extraction_method": Components['schemas']['PdfExtractionMethod'] | string; "content_profile": Components['schemas']['ContentProfile'] | string; "created_at": string; "locator_kind"?: string; "start_ms"?: number | null; "end_ms"?: number | null; "source_revision"?: number; "translated_text"?: string | null; "translation_source_revision"?: number | null; "translation_stale"?: boolean };
    ChunkUpdate: { "text": string };
    ContentProfile: string;
    DocumentList: { "items": Components['schemas']['DocumentRead'][] };
    DocumentOperationPhase: "uploading" | "processing" | "transcribing" | "translating" | "canceling" | "committing" | "canceled" | "completed" | "failed";
    DocumentOperationRead: { "id": string; "project_id": string; "document_id": string | null; "status": Components['schemas']['DocumentOperationStatus']; "phase": Components['schemas']['DocumentOperationPhase']; "cancellable": boolean; "error": string | null; "created_at": string; "updated_at": string };
    DocumentOperationStatus: "queued" | "running" | "cancel_requested" | "canceled" | "succeeded" | "failed";
    DocumentRead: { "id": string; "project_id": string; "filename": string; "sha256": string; "language_hint": string; "page_count": number; "has_text": boolean; "status": Components['schemas']['SourceDocumentStatus'] | string; "extraction_method": Components['schemas']['PdfExtractionMethod'] | string; "ocr_device": string | null; "ocr_fallback_reason": string | null; "ocr_duration_ms": number; "processed_page_count": number; "parse_wall_duration_ms": number; "render_duration_ms": number; "ocr_engine_duration_ms": number; "ocr_worker_count": number; "first_chunk_ms": number; "exam_item_count": number; "content_profile": Components['schemas']['ContentProfile'] | string; "classification_detail": string; "chunks_count": number; "created_at": string; "updated_at": string; "source_kind"?: string; "duration_ms"?: number | null; "transcription_status"?: string; "translation_status"?: string; "configured_transcription_model"?: string | null; "effective_transcription_model"?: string | null; "transcription_device"?: string | null; "transcription_warning"?: string | null };
    DraftGenerateRequest: { "limit"?: number; "strategy"?: Components['schemas']['DraftGenerationStrategy'] };
    DraftGenerationJobList: { "items": Components['schemas']['DraftGenerationJobRead'][] };
    DraftGenerationJobRead: { "id": string; "project_id": string; "document_id": string; "chunk_id": string; "page_number": number; "strategy": Components['schemas']['DraftGenerationStrategy']; "status": Components['schemas']['DraftGenerationJobStatus']; "phase": string; "cancellable": boolean; "provider": string; "model": string; "effective_provider": string | null; "effective_model": string | null; "fallback_reason": string | null; "generated_count": number; "retry_count": number; "last_error": string | null; "created_at": string; "updated_at": string };
    DraftGenerationJobStatus: "pending" | "running" | "cancel_requested" | "canceled" | "succeeded" | "skipped_provider_unavailable" | "skipped_missing_model" | "failed";
    DraftGenerationStrategy: string;
    DraftStatus: string;
    HTTPValidationError: { "detail"?: Components['schemas']['ValidationError'][] };
    HealthResponse: { "status": string; "app": string; "version": string; "python_version": string; "runtime_mode": string };
    LLMExecutionMode: string;
    LLMHealthRead: { "provider": string; "model": string; "available": boolean; "detail": string; "unavailable_reason"?: string | null; "configured_model"?: string | null; "effective_model"?: string | null; "fallback_models"?: string[]; "fallback_reason"?: string | null; "execution_mode"?: Components['schemas']['LLMExecutionMode'] | null; "execution_warning"?: string | null; "profile_id"?: string | null; "base_model"?: string | null; "modelfile_sha256"?: string | null; "profile_reason"?: string | null; "profile_warnings"?: string[] };
    LLMProviderName: string;
    LLMProviderPreference: string;
    LLMProviderSelectionRead: { "preference": Components['schemas']['LLMProviderPreference']; "selected_provider": Components['schemas']['LLMProviderName']; "effective_provider": Components['schemas']['LLMProviderName']; "configured_model": string; "effective_model": string; "selection_reason": string; "fallback_reason"?: string | null; "runtime_requirement_kind"?: Components['schemas']['RuntimeRequirementKind'] | null; "model_requirement_kind"?: Components['schemas']['RuntimeRequirementKind'] | null };
    MachineAcceleratorRead: { "kind": string; "name": string; "vendor"?: string | null; "memory_bytes"?: number | null; "driver_version"?: string | null; "device_id"?: string | null };
    MachineCpuRead: { "architecture": string; "name"?: string | null; "physical_cores"?: number | null; "logical_cores"?: number | null };
    MachineInventoryRead: { "platform": string; "platform_version": string; "architecture": string; "cpu": Components['schemas']['MachineCpuRead']; "ram": Components['schemas']['MachineRamRead']; "storage": Components['schemas']['MachineStorageRead']; "accelerators"?: Components['schemas']['MachineAcceleratorRead'][]; "warnings"?: string[]; "schema_version"?: number };
    MachineRamRead: { "total_bytes"?: number | null; "available_bytes"?: number | null };
    MachineStorageRead: { "path": string; "free_bytes"?: number | null; "total_bytes"?: number | null };
    ManualDraftGenerationOperationRead: { "id": string; "project_id": string; "document_id": string; "limit": number; "strategy": Components['schemas']['DraftGenerationStrategy']; "status": Components['schemas']['ManualDraftOperationStatus']; "phase": string; "cancellable": boolean; "provider": string; "model": string; "effective_provider"?: string | null; "effective_model"?: string | null; "fallback_reason"?: string | null; "generated_count": number; "unavailable_blocks"?: Components['schemas']['UnavailableDraftBlockRead'][]; "error"?: string | null; "created_at": string; "updated_at": string; "commit_started_at"?: string | null };
    ManualDraftOperationStatus: "queued" | "running" | "cancel_requested" | "canceled" | "succeeded" | "failed";
    ModelDownloadRead: { "id": string; "provider": string; "model": string; "status": Components['schemas']['cert_prep_contracts__runtime__RuntimeInstallationStatus']; "phase": string; "cancellable": boolean; "detail": string; "completed": number | null; "total": number | null; "created_at": string; "updated_at": string; "commit_started_at"?: string | null; "error"?: string | null };
    OllamaModelProfileRead: { "profile_id": string; "display_name": string; "description": string; "base_model": string; "local_model": string; "context_window": number; "system_prompt": string; "parameters"?: Record<string, unknown>; "min_total_ram_bytes"?: number | null; "min_available_ram_bytes"?: number | null; "min_free_disk_bytes"?: number | null; "min_vram_bytes"?: number | null; "auto_selectable": boolean; "explicit_opt_in_required": boolean; "fallback_profile_ids"?: string[] };
    OllamaProfileSelectionRead: { "profile_enabled": boolean; "profile_id"?: string | null; "selected_profile"?: Components['schemas']['OllamaModelProfileRead'] | null; "support_status": string; "reason": string; "fallback_profiles"?: Components['schemas']['OllamaModelProfileRead'][]; "fallback_models"?: string[]; "warnings"?: string[]; "inventory"?: Components['schemas']['MachineInventoryRead'] | null; "modelfile_sha256"?: string | null; "effective_model": string; "base_model"?: string | null };
    OllamaProfilesRead: { "items": Components['schemas']['OllamaModelProfileRead'][] };
    PageLocator: { "kind"?: string; "page": number; "boundingBox"?: unknown[] | null };
    PartialCapture: { "protocolVersion"?: string; "captureId": string; "source": Components['schemas']['CaptureSource']; "revision": number; "coveredUntilMs": number; "segments"?: Components['schemas']['RawCaptureSegment'][]; "sourceText"?: string; "extractionEngine"?: Components['schemas']['CaptureEngine'] | null; "updatedAt": string };
    PdfExtractionMethod: string;
    PracticeAttemptCreate: { "question_id": string; "selected_answer": string };
    PracticeAttemptRead: { "id": string; "session_id": string; "project_id": string; "question_id": string; "selected_answer": string; "is_correct": boolean; "created_at": string };
    PracticeSessionCreate: { "mode"?: Components['schemas']['PracticeSessionMode']; "document_id"?: string | null; "question_count"?: number | null; "random_seed"?: number | null; "wrong_attempt_ids"?: string[] | null };
    PracticeSessionList: { "items": Components['schemas']['PracticeSessionSummaryRead'][] };
    PracticeSessionMode: string;
    PracticeSessionQuestionRead: { "id": string; "question": string; "choices": string[]; "answer": string | null; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null; "document_id": string | null };
    PracticeSessionRead: { "id": string; "project_id": string; "question_ids": string[]; "questions": Components['schemas']['PracticeSessionQuestionRead'][]; "mode": Components['schemas']['PracticeSessionMode']; "document_id": string | null; "question_count": number; "random_seed": number | null; "status": Components['schemas']['PracticeSessionStatus']; "created_at": string; "completed_at": string | null; "abandoned_at": string | null; "attempts": Components['schemas']['PracticeAttemptRead'][] };
    PracticeSessionStatus: string;
    PracticeSessionSummaryRead: { "id": string; "project_id": string; "mode": Components['schemas']['PracticeSessionMode']; "document_id": string | null; "status": Components['schemas']['PracticeSessionStatus']; "created_at": string };
    ProjectCreate: { "name": string; "description"?: string };
    ProjectList: { "items": Components['schemas']['ProjectRead'][] };
    ProjectRead: { "id": string; "name": string; "description": string; "created_at": string; "updated_at": string };
    ProjectUpdate: { "name"?: string | null; "description"?: string | null };
    QuestionDraftCreate: { "question"?: string; "choices"?: string[]; "answer"?: string | null; "answer_key_source"?: Components['schemas']['AnswerKeySource'] | string; "rationale"?: string | null; "citation_page"?: number | null; "source_excerpt"?: string | null; "confidence"?: number | null; "document_id"?: string | null; "chunk_id"?: string | null; "source_order"?: number | null; "source_question_number"?: string | null; "item_kind"?: Components['schemas']['QuestionItemKind'] | string; "group_key"?: string | null; "group_prompt"?: string | null };
    QuestionDraftList: { "items": Components['schemas']['QuestionDraftRead'][] };
    QuestionDraftRead: { "id": string; "project_id": string; "document_id": string | null; "chunk_id": string | null; "question": string; "choices": string[]; "answer": string | null; "answer_key_source": Components['schemas']['AnswerKeySource'] | string; "rationale": string | null; "citation_page": number | null; "citation_locator_kind"?: string; "citation_start_ms"?: number | null; "citation_end_ms"?: number | null; "source_excerpt": string | null; "confidence": number | null; "source_order": number | null; "source_question_number": string | null; "item_kind": Components['schemas']['QuestionItemKind'] | string; "group_key": string | null; "group_prompt": string | null; "status": Components['schemas']['DraftStatus'] | string; "rejection_reason": string | null; "created_at": string; "updated_at": string };
    QuestionDraftUpdate: { "question"?: string | null; "choices"?: string[] | null; "answer"?: string | null; "answer_key_source"?: Components['schemas']['AnswerKeySource'] | string | null; "rationale"?: string | null; "citation_page"?: number | null; "source_excerpt"?: string | null; "confidence"?: number | null; "source_order"?: number | null; "source_question_number"?: string | null; "item_kind"?: Components['schemas']['QuestionItemKind'] | string | null; "group_key"?: string | null; "group_prompt"?: string | null };
    QuestionItemKind: string;
    RawCapture: { "schemaVersion"?: string; "diagnosticOnly"?: boolean; "source": Components['schemas']['CaptureSource']; "segments": Components['schemas']['RawCaptureSegment'][]; "sourceText": string; "extractionEngine": Components['schemas']['CaptureEngine']; "warnings"?: string[]; "createdAt": string };
    RawCaptureSegment: { "segmentId": string; "order": number; "locator": Components['schemas']['PageLocator'] | Components['schemas']['TimeLocator']; "text": string };
    RuntimeArtifactDescriptorV2: { "artifactUrl": string; "artifactFileName": string; "bytes": number; "sha256": string };
    RuntimeInstallation: { "installationId": string; "requirementId": string; "status": Components['schemas']['capture_runtime_client__private__generated_models__RuntimeInstallationStatus']; "progress": number; "error"?: Components['schemas']['CaptureFailureV2'] | null; "createdAt": string; "updatedAt": string; "completedAt"?: string | null };
    RuntimeInstallationRead: { "id": string; "kind": Components['schemas']['RuntimeRequirementKind']; "provider": string; "model": string; "status": Components['schemas']['cert_prep_contracts__runtime__RuntimeInstallationStatus']; "phase": string; "cancellable": boolean; "detail": string; "completed": number | null; "total": number | null; "created_at": string; "updated_at": string; "commit_started_at"?: string | null; "error"?: string | null };
    RuntimeInstallationV2: { "installationId": string; "requirementId": string; "status": Components['schemas']['capture_runtime_client__private__generated_models__RuntimeInstallationStatus']; "progress": number; "error"?: Components['schemas']['CaptureFailureV2'] | null; "createdAt": string; "updatedAt": string; "completedAt"?: string | null };
    RuntimeInstallations: { "items": Components['schemas']['RuntimeInstallationV2'][] };
    RuntimeReady: { "ready": boolean; "service": string; "apiVersion": string; "runtimeVersion": string; "captureDocumentSchemaVersion": string; "captureDocumentSchemaSha256"?: string | null; "schemaSha256"?: string | null; "contractSetVersion"?: string; "capabilities"?: Record<string, unknown>; "message"?: string | null };
    RuntimeRequirementKind: string;
    RuntimeRequirementRead: { "kind": Components['schemas']['RuntimeRequirementKind']; "label": string; "available": boolean; "detail": string; "unavailable_reason": string | null; "version"?: string | null; "bytes"?: number | null; "installed_path"?: string | null };
    RuntimeRequirementStatus: string;
    RuntimeRequirementV2: { "requirementId": string; "kind": string; "displayName": string; "status": Components['schemas']['RuntimeRequirementStatus']; "requiredFor": string[]; "installStrategy": string; "detail"?: string | null; "artifact"?: Components['schemas']['RuntimeArtifactDescriptorV2'] | null };
    RuntimeRequirements: { "items": Components['schemas']['RuntimeRequirementV2'][] };
    RuntimeRequirementsRead: { "items": Components['schemas']['RuntimeRequirementRead'][] };
    SourceDocumentStatus: string;
    StartRuntimeInstallationRequest: { "requirementId": string; "consent": boolean };
    StreamingCaptureStatus: string;
    TimeLocator: { "kind"?: string; "startMs": number; "endMs": number };
    UnavailableDraftBlockRead: { "status"?: string; "chunk_id": string; "citation_page": number; "source_excerpt": string; "source_order"?: number | null; "source_question_number"?: string | null; "reason": string };
    ValidationError: { "loc": (string | number)[]; "msg": string; "type": string; "input"?: unknown; "ctx"?: Record<string, unknown> };
    WrongAnswerClusterRead: { "document_id": string | null; "citation_page": number | null; "current_wrong_count": number; "cleared_count": number; "last_wrong_at": string | null };
    WrongAnswerExplanationRead: { "attempt_id": string; "explanation": string; "provider": string; "model": string; "grounded_fields": Components['schemas']['WrongAnswerGroundedFields']; "fallback": boolean };
    WrongAnswerGroundedFields: { "question": string; "selected_answer": string; "correct_answer": string | null; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null };
    WrongAnswerList: { "items": Components['schemas']['WrongAnswerRead'][] };
    WrongAnswerRead: { "attempt_id": string; "session_id": string; "question_id": string; "question": string; "selected_answer": string; "correct_answer": string | null; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null; "document_id": string | null; "created_at": string };
    WrongAnswerRepeatedMissRead: { "question_id": string; "question": string; "document_id": string | null; "citation_page": number | null; "source_excerpt": string | null; "miss_count": number; "last_wrong_at": string };
    WrongAnswerSummaryRead: { "current_wrong_count": number; "cleared_count": number; "last_wrong_date": string | null; "repeated_misses": Components['schemas']['WrongAnswerRepeatedMissRead'][]; "clusters": Components['schemas']['WrongAnswerClusterRead'][] };
    capture_runtime_client__private__generated_models__RuntimeInstallationStatus: string;
    cert_prep_contracts__runtime__RuntimeInstallationStatus: string;
  };
}

export type AnswerKeySource = Components['schemas']['AnswerKeySource'];
export type ApiErrorRead = Components['schemas']['ApiErrorRead'];
export type Body_create_capture_projects__project_id__capture_workbench_captures_post = Components['schemas']['Body_create_capture_projects__project_id__capture_workbench_captures_post'];
export type Body_upload_document_projects__project_id__documents_post = Components['schemas']['Body_upload_document_projects__project_id__documents_post'];
export type CaptureBlock = Components['schemas']['CaptureBlock'];
export type CaptureDocument = Components['schemas']['CaptureDocument'];
export type CaptureEngine = Components['schemas']['CaptureEngine'];
export type CaptureFailureV2 = Components['schemas']['CaptureFailureV2'];
export type CaptureReview = Components['schemas']['CaptureReview'];
export type CaptureReviewEdit = Components['schemas']['CaptureReviewEdit'];
export type CaptureReviewOperationRead = Components['schemas']['CaptureReviewOperationRead'];
export type CaptureReviewStructureRequest = Components['schemas']['CaptureReviewStructureRequest'];
export type CaptureSource = Components['schemas']['CaptureSource'];
export type CaptureSourceKind = Components['schemas']['CaptureSourceKind'];
export type CaptureStreamingCommitRequest = Components['schemas']['CaptureStreamingCommitRequest'];
export type CaptureStreamingFailureRequest = Components['schemas']['CaptureStreamingFailureRequest'];
export type CaptureStreamingResultRead = Components['schemas']['CaptureStreamingResultRead'];
export type ChunkList = Components['schemas']['ChunkList'];
export type ChunkRead = Components['schemas']['ChunkRead'];
export type ChunkUpdate = Components['schemas']['ChunkUpdate'];
export type ContentProfile = Components['schemas']['ContentProfile'];
export type DocumentList = Components['schemas']['DocumentList'];
export type DocumentOperationPhase = Components['schemas']['DocumentOperationPhase'];
export type DocumentOperationRead = Components['schemas']['DocumentOperationRead'];
export type DocumentOperationStatus = Components['schemas']['DocumentOperationStatus'];
export type DocumentRead = Components['schemas']['DocumentRead'];
export type DraftGenerateRequest = Components['schemas']['DraftGenerateRequest'];
export type DraftGenerationJobList = Components['schemas']['DraftGenerationJobList'];
export type DraftGenerationJobRead = Components['schemas']['DraftGenerationJobRead'];
export type DraftGenerationJobStatus = Components['schemas']['DraftGenerationJobStatus'];
export type DraftGenerationStrategy = Components['schemas']['DraftGenerationStrategy'];
export type DraftStatus = Components['schemas']['DraftStatus'];
export type HTTPValidationError = Components['schemas']['HTTPValidationError'];
export type HealthResponse = Components['schemas']['HealthResponse'];
export type LLMExecutionMode = Components['schemas']['LLMExecutionMode'];
export type LLMHealthRead = Components['schemas']['LLMHealthRead'];
export type LLMProviderName = Components['schemas']['LLMProviderName'];
export type LLMProviderPreference = Components['schemas']['LLMProviderPreference'];
export type LLMProviderSelectionRead = Components['schemas']['LLMProviderSelectionRead'];
export type MachineAcceleratorRead = Components['schemas']['MachineAcceleratorRead'];
export type MachineCpuRead = Components['schemas']['MachineCpuRead'];
export type MachineInventoryRead = Components['schemas']['MachineInventoryRead'];
export type MachineRamRead = Components['schemas']['MachineRamRead'];
export type MachineStorageRead = Components['schemas']['MachineStorageRead'];
export type ManualDraftGenerationOperationRead = Components['schemas']['ManualDraftGenerationOperationRead'];
export type ManualDraftOperationStatus = Components['schemas']['ManualDraftOperationStatus'];
export type ModelDownloadRead = Components['schemas']['ModelDownloadRead'];
export type OllamaModelProfileRead = Components['schemas']['OllamaModelProfileRead'];
export type OllamaProfileSelectionRead = Components['schemas']['OllamaProfileSelectionRead'];
export type OllamaProfilesRead = Components['schemas']['OllamaProfilesRead'];
export type PageLocator = Components['schemas']['PageLocator'];
export type PartialCapture = Components['schemas']['PartialCapture'];
export type PdfExtractionMethod = Components['schemas']['PdfExtractionMethod'];
export type PracticeAttemptCreate = Components['schemas']['PracticeAttemptCreate'];
export type PracticeAttemptRead = Components['schemas']['PracticeAttemptRead'];
export type PracticeSessionCreate = Components['schemas']['PracticeSessionCreate'];
export type PracticeSessionList = Components['schemas']['PracticeSessionList'];
export type PracticeSessionMode = Components['schemas']['PracticeSessionMode'];
export type PracticeSessionQuestionRead = Components['schemas']['PracticeSessionQuestionRead'];
export type PracticeSessionRead = Components['schemas']['PracticeSessionRead'];
export type PracticeSessionStatus = Components['schemas']['PracticeSessionStatus'];
export type PracticeSessionSummaryRead = Components['schemas']['PracticeSessionSummaryRead'];
export type ProjectCreate = Components['schemas']['ProjectCreate'];
export type ProjectList = Components['schemas']['ProjectList'];
export type ProjectRead = Components['schemas']['ProjectRead'];
export type ProjectUpdate = Components['schemas']['ProjectUpdate'];
export type QuestionDraftCreate = Components['schemas']['QuestionDraftCreate'];
export type QuestionDraftList = Components['schemas']['QuestionDraftList'];
export type QuestionDraftRead = Components['schemas']['QuestionDraftRead'];
export type QuestionDraftUpdate = Components['schemas']['QuestionDraftUpdate'];
export type QuestionItemKind = Components['schemas']['QuestionItemKind'];
export type RawCapture = Components['schemas']['RawCapture'];
export type RawCaptureSegment = Components['schemas']['RawCaptureSegment'];
export type RuntimeArtifactDescriptorV2 = Components['schemas']['RuntimeArtifactDescriptorV2'];
export type RuntimeInstallation = Components['schemas']['RuntimeInstallation'];
export type RuntimeInstallationRead = Components['schemas']['RuntimeInstallationRead'];
export type RuntimeInstallationV2 = Components['schemas']['RuntimeInstallationV2'];
export type RuntimeInstallations = Components['schemas']['RuntimeInstallations'];
export type RuntimeReady = Components['schemas']['RuntimeReady'];
export type RuntimeRequirementKind = Components['schemas']['RuntimeRequirementKind'];
export type RuntimeRequirementRead = Components['schemas']['RuntimeRequirementRead'];
export type RuntimeRequirementStatus = Components['schemas']['RuntimeRequirementStatus'];
export type RuntimeRequirementV2 = Components['schemas']['RuntimeRequirementV2'];
export type RuntimeRequirements = Components['schemas']['RuntimeRequirements'];
export type RuntimeRequirementsRead = Components['schemas']['RuntimeRequirementsRead'];
export type SourceDocumentStatus = Components['schemas']['SourceDocumentStatus'];
export type StartRuntimeInstallationRequest = Components['schemas']['StartRuntimeInstallationRequest'];
export type StreamingCaptureStatus = Components['schemas']['StreamingCaptureStatus'];
export type TimeLocator = Components['schemas']['TimeLocator'];
export type UnavailableDraftBlockRead = Components['schemas']['UnavailableDraftBlockRead'];
export type ValidationError = Components['schemas']['ValidationError'];
export type WrongAnswerClusterRead = Components['schemas']['WrongAnswerClusterRead'];
export type WrongAnswerExplanationRead = Components['schemas']['WrongAnswerExplanationRead'];
export type WrongAnswerGroundedFields = Components['schemas']['WrongAnswerGroundedFields'];
export type WrongAnswerList = Components['schemas']['WrongAnswerList'];
export type WrongAnswerRead = Components['schemas']['WrongAnswerRead'];
export type WrongAnswerRepeatedMissRead = Components['schemas']['WrongAnswerRepeatedMissRead'];
export type WrongAnswerSummaryRead = Components['schemas']['WrongAnswerSummaryRead'];
export type capture_runtime_client__private__generated_models__RuntimeInstallationStatus = Components['schemas']['capture_runtime_client__private__generated_models__RuntimeInstallationStatus'];
export type cert_prep_contracts__runtime__RuntimeInstallationStatus = Components['schemas']['cert_prep_contracts__runtime__RuntimeInstallationStatus'];

export type CertPrepHttpMethod = 'DELETE' | 'GET' | 'PATCH' | 'POST';

export interface CertPrepRequestOptions {
  headers?: Readonly<Record<string, string>>;
  signal?: AbortSignal;
}

export interface CertPrepHttpRequest {
  method: CertPrepHttpMethod;
  path: string;
  body?: unknown;
  headers?: Readonly<Record<string, string>>;
  signal?: AbortSignal;
  responseType?: 'blob';
}

export interface CertPrepTransport {
  request<TResponse>(request: CertPrepHttpRequest): Observable<TResponse>;
}

export interface CertPrepGeneratedClient {
  health(options?: CertPrepRequestOptions): Observable<Components['schemas']['HealthResponse']>;
  listProjects(options?: CertPrepRequestOptions): Observable<Components['schemas']['ProjectList']>;
  createProject(body: Components['schemas']['ProjectCreate'], options?: CertPrepRequestOptions): Observable<Components['schemas']['ProjectRead']>;
  getProject(projectId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['ProjectRead']>;
  updateProject(projectId: string, body: Components['schemas']['ProjectUpdate'], options?: CertPrepRequestOptions): Observable<Components['schemas']['ProjectRead']>;
  deleteProject(projectId: string, options?: CertPrepRequestOptions): Observable<void>;
  listDocuments(projectId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['DocumentList']>;
  uploadDocument(projectId: string, body: FormData, options?: CertPrepRequestOptions): Observable<Components['schemas']['DocumentRead']>;
  getDocument(projectId: string, documentId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['DocumentRead']>;
  getDocumentMarkdown(projectId: string, documentId: string, options?: CertPrepRequestOptions): Observable<Blob>;
  getDocumentAudioSource(projectId: string, documentId: string, options?: CertPrepRequestOptions): Observable<Blob>;
  cancelDocumentProcessing(projectId: string, documentId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['DocumentOperationRead']>;
  retryDocumentProcessing(projectId: string, documentId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['DocumentOperationRead']>;
  listDocumentChunks(projectId: string, documentId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['ChunkList']>;
  updateDocumentChunk(projectId: string, documentId: string, chunkId: string, body: Components['schemas']['ChunkUpdate'], options?: CertPrepRequestOptions): Observable<Components['schemas']['ChunkRead']>;
  translateDocumentChunk(projectId: string, documentId: string, chunkId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['ChunkRead']>;
  translateDocumentStaleChunks(projectId: string, documentId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['ChunkList']>;
  getDocumentOperation(projectId: string, operationId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['DocumentOperationRead']>;
  cancelDocumentOperation(projectId: string, operationId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['DocumentOperationRead']>;
  generateDocumentDrafts(projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions): Observable<Components['schemas']['QuestionDraftList']>;
  listDocumentDraftJobs(projectId: string, documentId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['DraftGenerationJobList']>;
  retryDocumentDraftJobs(projectId: string, documentId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['DraftGenerationJobList']>;
  cancelDocumentDraftJob(projectId: string, documentId: string, jobId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['DraftGenerationJobRead']>;
  startManualDraftOperation(projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions): Observable<Components['schemas']['ManualDraftGenerationOperationRead']>;
  getManualDraftOperation(projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['ManualDraftGenerationOperationRead']>;
  cancelManualDraftOperation(projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['ManualDraftGenerationOperationRead']>;
  createQuestionDraft(projectId: string, body: Components['schemas']['QuestionDraftCreate'], options?: CertPrepRequestOptions): Observable<Components['schemas']['QuestionDraftRead']>;
  listQuestionDrafts(projectId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['QuestionDraftList']>;
  updateQuestionDraft(projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate'], options?: CertPrepRequestOptions): Observable<Components['schemas']['QuestionDraftRead']>;
  createPracticeSession(projectId: string, body: Components['schemas']['PracticeSessionCreate'], options?: CertPrepRequestOptions): Observable<Components['schemas']['PracticeSessionRead']>;
  listActivePracticeSessions(projectId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['PracticeSessionList']>;
  getPracticeSession(projectId: string, sessionId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['PracticeSessionRead']>;
  abandonPracticeSession(projectId: string, sessionId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['PracticeSessionRead']>;
  recordPracticeAttempt(projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate'], options?: CertPrepRequestOptions): Observable<Components['schemas']['PracticeAttemptRead']>;
  listWrongAnswers(projectId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['WrongAnswerList']>;
  summarizeWrongAnswers(projectId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['WrongAnswerSummaryRead']>;
  explainWrongAnswer(projectId: string, attemptId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['WrongAnswerExplanationRead']>;
  llmHealth(options?: CertPrepRequestOptions): Observable<Components['schemas']['LLMHealthRead']>;
  llmProviderSelection(options?: CertPrepRequestOptions): Observable<Components['schemas']['LLMProviderSelectionRead']>;
  llmProfiles(options?: CertPrepRequestOptions): Observable<Components['schemas']['OllamaProfilesRead']>;
  llmProfileSelection(options?: CertPrepRequestOptions): Observable<Components['schemas']['OllamaProfileSelectionRead']>;
  startModelDownload(options?: CertPrepRequestOptions): Observable<Components['schemas']['ModelDownloadRead']>;
  getModelDownload(jobId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['ModelDownloadRead']>;
  cancelModelDownload(jobId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['ModelDownloadRead']>;
  runtimeRequirements(options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeRequirementsRead']>;
  machineInventory(options?: CertPrepRequestOptions): Observable<Components['schemas']['MachineInventoryRead']>;
  startRuntimeInstallation(kind: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeInstallationRead']>;
  getRuntimeInstallation(jobId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeInstallationRead']>;
  cancelRuntimeInstallation(jobId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeInstallationRead']>;
  captureRuntimeReady(options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeReady']>;
  captureRuntimeRequirements(options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeRequirements']>;
  startCaptureRuntimeInstallation(body: Components['schemas']['StartRuntimeInstallationRequest'], options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeInstallation']>;
  captureRuntimeInstallations(options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeInstallations']>;
  captureRuntimeInstallation(installationId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeInstallation']>;
  cancelCaptureRuntimeInstallation(installationId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['RuntimeInstallation']>;
  createCapture(projectId: string, body: FormData, options?: CertPrepRequestOptions): Observable<Components['schemas']['CaptureReviewOperationRead']>;
  getCapture(projectId: string, captureId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['CaptureReviewOperationRead']>;
  deleteCapture(projectId: string, captureId: string, options?: CertPrepRequestOptions): Observable<void>;
  captureEvents(projectId: string, captureId: string, options?: CertPrepRequestOptions): Observable<unknown>;
  getPartial(projectId: string, captureId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['PartialCapture']>;
  getRaw(projectId: string, captureId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['RawCapture']>;
  structureCapture(projectId: string, captureId: string, body: Components['schemas']['CaptureReviewStructureRequest'], options?: CertPrepRequestOptions): Observable<Components['schemas']['CaptureDocument']>;
  commitCapture(projectId: string, captureId: string, body: Components['schemas']['CaptureStreamingCommitRequest'], options?: CertPrepRequestOptions): Observable<Components['schemas']['CaptureReviewOperationRead']>;
  reportStructuringFailure(projectId: string, captureId: string, body: Components['schemas']['CaptureStreamingFailureRequest'], options?: CertPrepRequestOptions): Observable<Components['schemas']['CaptureReviewOperationRead']>;
  cancelCapture(projectId: string, captureId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['CaptureReviewOperationRead']>;
  getResult(projectId: string, captureId: string, options?: CertPrepRequestOptions): Observable<Components['schemas']['CaptureStreamingResultRead']>;
}

export interface CertPrepRequestFactory {
  health(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  listProjects(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  createProject(body: Components['schemas']['ProjectCreate'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getProject(projectId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  updateProject(projectId: string, body: Components['schemas']['ProjectUpdate'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  deleteProject(projectId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  listDocuments(projectId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  uploadDocument(projectId: string, body: FormData, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getDocument(projectId: string, documentId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getDocumentMarkdown(projectId: string, documentId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getDocumentAudioSource(projectId: string, documentId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  cancelDocumentProcessing(projectId: string, documentId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  retryDocumentProcessing(projectId: string, documentId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  listDocumentChunks(projectId: string, documentId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  updateDocumentChunk(projectId: string, documentId: string, chunkId: string, body: Components['schemas']['ChunkUpdate'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  translateDocumentChunk(projectId: string, documentId: string, chunkId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  translateDocumentStaleChunks(projectId: string, documentId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getDocumentOperation(projectId: string, operationId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  cancelDocumentOperation(projectId: string, operationId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  generateDocumentDrafts(projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  listDocumentDraftJobs(projectId: string, documentId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  retryDocumentDraftJobs(projectId: string, documentId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  cancelDocumentDraftJob(projectId: string, documentId: string, jobId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  startManualDraftOperation(projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getManualDraftOperation(projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  cancelManualDraftOperation(projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  createQuestionDraft(projectId: string, body: Components['schemas']['QuestionDraftCreate'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  listQuestionDrafts(projectId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  updateQuestionDraft(projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  createPracticeSession(projectId: string, body: Components['schemas']['PracticeSessionCreate'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  listActivePracticeSessions(projectId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getPracticeSession(projectId: string, sessionId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  abandonPracticeSession(projectId: string, sessionId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  recordPracticeAttempt(projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  listWrongAnswers(projectId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  summarizeWrongAnswers(projectId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  explainWrongAnswer(projectId: string, attemptId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  llmHealth(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  llmProviderSelection(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  llmProfiles(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  llmProfileSelection(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  startModelDownload(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getModelDownload(jobId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  cancelModelDownload(jobId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  runtimeRequirements(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  machineInventory(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  startRuntimeInstallation(kind: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getRuntimeInstallation(jobId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  cancelRuntimeInstallation(jobId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  captureRuntimeReady(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  captureRuntimeRequirements(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  startCaptureRuntimeInstallation(body: Components['schemas']['StartRuntimeInstallationRequest'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  captureRuntimeInstallations(options?: CertPrepRequestOptions): CertPrepHttpRequest;
  captureRuntimeInstallation(installationId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  cancelCaptureRuntimeInstallation(installationId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  createCapture(projectId: string, body: FormData, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getCapture(projectId: string, captureId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  deleteCapture(projectId: string, captureId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  captureEvents(projectId: string, captureId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getPartial(projectId: string, captureId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getRaw(projectId: string, captureId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  structureCapture(projectId: string, captureId: string, body: Components['schemas']['CaptureReviewStructureRequest'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  commitCapture(projectId: string, captureId: string, body: Components['schemas']['CaptureStreamingCommitRequest'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  reportStructuringFailure(projectId: string, captureId: string, body: Components['schemas']['CaptureStreamingFailureRequest'], options?: CertPrepRequestOptions): CertPrepHttpRequest;
  cancelCapture(projectId: string, captureId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
  getResult(projectId: string, captureId: string, options?: CertPrepRequestOptions): CertPrepHttpRequest;
}

export function createCertPrepRequestFactory(): CertPrepRequestFactory {
  return {
    health: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/health", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    listProjects: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/projects", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    createProject: (body: Components['schemas']['ProjectCreate'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: "/projects", body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getProject: (projectId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    updateProject: (projectId: string, body: Components['schemas']['ProjectUpdate'], options?: CertPrepRequestOptions) => {
      return { method: 'PATCH' as const, path: `/projects/${encodeURIComponent(projectId)}`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    deleteProject: (projectId: string, options?: CertPrepRequestOptions) => {
      return { method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    listDocuments: (projectId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    uploadDocument: (projectId: string, body: FormData, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getDocument: (projectId: string, documentId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getDocumentMarkdown: (projectId: string, documentId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/markdown`, responseType: 'blob' as const, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getDocumentAudioSource: (projectId: string, documentId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/source`, responseType: 'blob' as const, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    cancelDocumentProcessing: (projectId: string, documentId: string, options?: CertPrepRequestOptions) => {
      return { method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/processing`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    retryDocumentProcessing: (projectId: string, documentId: string, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/retry`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    listDocumentChunks: (projectId: string, documentId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/chunks`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    updateDocumentChunk: (projectId: string, documentId: string, chunkId: string, body: Components['schemas']['ChunkUpdate'], options?: CertPrepRequestOptions) => {
      return { method: 'PATCH' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/chunks/${encodeURIComponent(chunkId)}`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    translateDocumentChunk: (projectId: string, documentId: string, chunkId: string, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/chunks/${encodeURIComponent(chunkId)}/translation`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    translateDocumentStaleChunks: (projectId: string, documentId: string, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/translations`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getDocumentOperation: (projectId: string, operationId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/document-operations/${encodeURIComponent(operationId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    cancelDocumentOperation: (projectId: string, operationId: string, options?: CertPrepRequestOptions) => {
      return { method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}/document-operations/${encodeURIComponent(operationId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    generateDocumentDrafts: (projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/drafts`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    listDocumentDraftJobs: (projectId: string, documentId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-jobs`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    retryDocumentDraftJobs: (projectId: string, documentId: string, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-jobs/retry`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    cancelDocumentDraftJob: (projectId: string, documentId: string, jobId: string, options?: CertPrepRequestOptions) => {
      return { method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-jobs/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    startManualDraftOperation: (projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-operations`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getManualDraftOperation: (projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-operations/${encodeURIComponent(operationId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    cancelManualDraftOperation: (projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions) => {
      return { method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-operations/${encodeURIComponent(operationId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    createQuestionDraft: (projectId: string, body: Components['schemas']['QuestionDraftCreate'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    listQuestionDrafts: (projectId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    updateQuestionDraft: (projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate'], options?: CertPrepRequestOptions) => {
      return { method: 'PATCH' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts/${encodeURIComponent(draftId)}`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    createPracticeSession: (projectId: string, body: Components['schemas']['PracticeSessionCreate'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    listActivePracticeSessions: (projectId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getPracticeSession: (projectId: string, sessionId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    abandonPracticeSession: (projectId: string, sessionId: string, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}/abandon`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    recordPracticeAttempt: (projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}/attempts`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    listWrongAnswers: (projectId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/wrong-answers`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    summarizeWrongAnswers: (projectId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/wrong-answers/summary`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    explainWrongAnswer: (projectId: string, attemptId: string, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/wrong-answers/${encodeURIComponent(attemptId)}/explanation`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    llmHealth: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/llm/health", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    llmProviderSelection: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/llm/provider-selection", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    llmProfiles: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/llm/profiles", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    llmProfileSelection: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/llm/profile-selection", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    startModelDownload: (options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: "/llm/model-downloads", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getModelDownload: (jobId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/llm/model-downloads/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    cancelModelDownload: (jobId: string, options?: CertPrepRequestOptions) => {
      return { method: 'DELETE' as const, path: `/llm/model-downloads/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    runtimeRequirements: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/runtime/requirements", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    machineInventory: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/runtime/machine-inventory", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    startRuntimeInstallation: (kind: string, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/runtime/installations/${encodeURIComponent(kind)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getRuntimeInstallation: (jobId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/runtime/installations/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    cancelRuntimeInstallation: (jobId: string, options?: CertPrepRequestOptions) => {
      return { method: 'DELETE' as const, path: `/runtime/installations/${encodeURIComponent(jobId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    captureRuntimeReady: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/capture-runtime/ready", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    captureRuntimeRequirements: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/capture-runtime/requirements", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    startCaptureRuntimeInstallation: (body: Components['schemas']['StartRuntimeInstallationRequest'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: "/capture-runtime/installations", body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    captureRuntimeInstallations: (options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: "/capture-runtime/installations", ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    captureRuntimeInstallation: (installationId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/capture-runtime/installations/${encodeURIComponent(installationId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    cancelCaptureRuntimeInstallation: (installationId: string, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/capture-runtime/installations/${encodeURIComponent(installationId)}/cancel`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    createCapture: (projectId: string, body: FormData, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getCapture: (projectId: string, captureId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    deleteCapture: (projectId: string, captureId: string, options?: CertPrepRequestOptions) => {
      return { method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    captureEvents: (projectId: string, captureId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}/events`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getPartial: (projectId: string, captureId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}/partial`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getRaw: (projectId: string, captureId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}/raw`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    structureCapture: (projectId: string, captureId: string, body: Components['schemas']['CaptureReviewStructureRequest'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}/structure`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    commitCapture: (projectId: string, captureId: string, body: Components['schemas']['CaptureStreamingCommitRequest'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}/structure/commit`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    reportStructuringFailure: (projectId: string, captureId: string, body: Components['schemas']['CaptureStreamingFailureRequest'], options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}/structure/failure`, body, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    cancelCapture: (projectId: string, captureId: string, options?: CertPrepRequestOptions) => {
      return { method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}/cancel`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
    getResult: (projectId: string, captureId: string, options?: CertPrepRequestOptions) => {
      return { method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/capture-workbench/captures/${encodeURIComponent(captureId)}/result`, ...(options?.headers === undefined ? {} : { headers: options.headers }), ...(options?.signal === undefined ? {} : { signal: options.signal }) };
    },
  };
}

export function createCertPrepGeneratedClient(
  transport: CertPrepTransport,
): CertPrepGeneratedClient {
  const requests = createCertPrepRequestFactory();
  return {
    health: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['HealthResponse']>(requests.health(options)),
    listProjects: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ProjectList']>(requests.listProjects(options)),
    createProject: (body: Components['schemas']['ProjectCreate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ProjectRead']>(requests.createProject(body, options)),
    getProject: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ProjectRead']>(requests.getProject(projectId, options)),
    updateProject: (projectId: string, body: Components['schemas']['ProjectUpdate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ProjectRead']>(requests.updateProject(projectId, body, options)),
    deleteProject: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<void>(requests.deleteProject(projectId, options)),
    listDocuments: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentList']>(requests.listDocuments(projectId, options)),
    uploadDocument: (projectId: string, body: FormData, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentRead']>(requests.uploadDocument(projectId, body, options)),
    getDocument: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentRead']>(requests.getDocument(projectId, documentId, options)),
    getDocumentMarkdown: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Blob>(requests.getDocumentMarkdown(projectId, documentId, options)),
    getDocumentAudioSource: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Blob>(requests.getDocumentAudioSource(projectId, documentId, options)),
    cancelDocumentProcessing: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentOperationRead']>(requests.cancelDocumentProcessing(projectId, documentId, options)),
    retryDocumentProcessing: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentOperationRead']>(requests.retryDocumentProcessing(projectId, documentId, options)),
    listDocumentChunks: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ChunkList']>(requests.listDocumentChunks(projectId, documentId, options)),
    updateDocumentChunk: (projectId: string, documentId: string, chunkId: string, body: Components['schemas']['ChunkUpdate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ChunkRead']>(requests.updateDocumentChunk(projectId, documentId, chunkId, body, options)),
    translateDocumentChunk: (projectId: string, documentId: string, chunkId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ChunkRead']>(requests.translateDocumentChunk(projectId, documentId, chunkId, options)),
    translateDocumentStaleChunks: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ChunkList']>(requests.translateDocumentStaleChunks(projectId, documentId, options)),
    getDocumentOperation: (projectId: string, operationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentOperationRead']>(requests.getDocumentOperation(projectId, operationId, options)),
    cancelDocumentOperation: (projectId: string, operationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DocumentOperationRead']>(requests.cancelDocumentOperation(projectId, operationId, options)),
    generateDocumentDrafts: (projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['QuestionDraftList']>(requests.generateDocumentDrafts(projectId, documentId, body, options)),
    listDocumentDraftJobs: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DraftGenerationJobList']>(requests.listDocumentDraftJobs(projectId, documentId, options)),
    retryDocumentDraftJobs: (projectId: string, documentId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DraftGenerationJobList']>(requests.retryDocumentDraftJobs(projectId, documentId, options)),
    cancelDocumentDraftJob: (projectId: string, documentId: string, jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['DraftGenerationJobRead']>(requests.cancelDocumentDraftJob(projectId, documentId, jobId, options)),
    startManualDraftOperation: (projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ManualDraftGenerationOperationRead']>(requests.startManualDraftOperation(projectId, documentId, body, options)),
    getManualDraftOperation: (projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ManualDraftGenerationOperationRead']>(requests.getManualDraftOperation(projectId, documentId, operationId, options)),
    cancelManualDraftOperation: (projectId: string, documentId: string, operationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ManualDraftGenerationOperationRead']>(requests.cancelManualDraftOperation(projectId, documentId, operationId, options)),
    createQuestionDraft: (projectId: string, body: Components['schemas']['QuestionDraftCreate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['QuestionDraftRead']>(requests.createQuestionDraft(projectId, body, options)),
    listQuestionDrafts: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['QuestionDraftList']>(requests.listQuestionDrafts(projectId, options)),
    updateQuestionDraft: (projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['QuestionDraftRead']>(requests.updateQuestionDraft(projectId, draftId, body, options)),
    createPracticeSession: (projectId: string, body: Components['schemas']['PracticeSessionCreate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeSessionRead']>(requests.createPracticeSession(projectId, body, options)),
    listActivePracticeSessions: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeSessionList']>(requests.listActivePracticeSessions(projectId, options)),
    getPracticeSession: (projectId: string, sessionId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeSessionRead']>(requests.getPracticeSession(projectId, sessionId, options)),
    abandonPracticeSession: (projectId: string, sessionId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeSessionRead']>(requests.abandonPracticeSession(projectId, sessionId, options)),
    recordPracticeAttempt: (projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PracticeAttemptRead']>(requests.recordPracticeAttempt(projectId, sessionId, body, options)),
    listWrongAnswers: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['WrongAnswerList']>(requests.listWrongAnswers(projectId, options)),
    summarizeWrongAnswers: (projectId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['WrongAnswerSummaryRead']>(requests.summarizeWrongAnswers(projectId, options)),
    explainWrongAnswer: (projectId: string, attemptId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['WrongAnswerExplanationRead']>(requests.explainWrongAnswer(projectId, attemptId, options)),
    llmHealth: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['LLMHealthRead']>(requests.llmHealth(options)),
    llmProviderSelection: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['LLMProviderSelectionRead']>(requests.llmProviderSelection(options)),
    llmProfiles: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['OllamaProfilesRead']>(requests.llmProfiles(options)),
    llmProfileSelection: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['OllamaProfileSelectionRead']>(requests.llmProfileSelection(options)),
    startModelDownload: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ModelDownloadRead']>(requests.startModelDownload(options)),
    getModelDownload: (jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ModelDownloadRead']>(requests.getModelDownload(jobId, options)),
    cancelModelDownload: (jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['ModelDownloadRead']>(requests.cancelModelDownload(jobId, options)),
    runtimeRequirements: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeRequirementsRead']>(requests.runtimeRequirements(options)),
    machineInventory: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['MachineInventoryRead']>(requests.machineInventory(options)),
    startRuntimeInstallation: (kind: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallationRead']>(requests.startRuntimeInstallation(kind, options)),
    getRuntimeInstallation: (jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallationRead']>(requests.getRuntimeInstallation(jobId, options)),
    cancelRuntimeInstallation: (jobId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallationRead']>(requests.cancelRuntimeInstallation(jobId, options)),
    captureRuntimeReady: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeReady']>(requests.captureRuntimeReady(options)),
    captureRuntimeRequirements: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeRequirements']>(requests.captureRuntimeRequirements(options)),
    startCaptureRuntimeInstallation: (body: Components['schemas']['StartRuntimeInstallationRequest'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallation']>(requests.startCaptureRuntimeInstallation(body, options)),
    captureRuntimeInstallations: (options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallations']>(requests.captureRuntimeInstallations(options)),
    captureRuntimeInstallation: (installationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallation']>(requests.captureRuntimeInstallation(installationId, options)),
    cancelCaptureRuntimeInstallation: (installationId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RuntimeInstallation']>(requests.cancelCaptureRuntimeInstallation(installationId, options)),
    createCapture: (projectId: string, body: FormData, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['CaptureReviewOperationRead']>(requests.createCapture(projectId, body, options)),
    getCapture: (projectId: string, captureId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['CaptureReviewOperationRead']>(requests.getCapture(projectId, captureId, options)),
    deleteCapture: (projectId: string, captureId: string, options?: CertPrepRequestOptions) =>
      transport.request<void>(requests.deleteCapture(projectId, captureId, options)),
    captureEvents: (projectId: string, captureId: string, options?: CertPrepRequestOptions) =>
      transport.request<unknown>(requests.captureEvents(projectId, captureId, options)),
    getPartial: (projectId: string, captureId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['PartialCapture']>(requests.getPartial(projectId, captureId, options)),
    getRaw: (projectId: string, captureId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['RawCapture']>(requests.getRaw(projectId, captureId, options)),
    structureCapture: (projectId: string, captureId: string, body: Components['schemas']['CaptureReviewStructureRequest'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['CaptureDocument']>(requests.structureCapture(projectId, captureId, body, options)),
    commitCapture: (projectId: string, captureId: string, body: Components['schemas']['CaptureStreamingCommitRequest'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['CaptureReviewOperationRead']>(requests.commitCapture(projectId, captureId, body, options)),
    reportStructuringFailure: (projectId: string, captureId: string, body: Components['schemas']['CaptureStreamingFailureRequest'], options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['CaptureReviewOperationRead']>(requests.reportStructuringFailure(projectId, captureId, body, options)),
    cancelCapture: (projectId: string, captureId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['CaptureReviewOperationRead']>(requests.cancelCapture(projectId, captureId, options)),
    getResult: (projectId: string, captureId: string, options?: CertPrepRequestOptions) =>
      transport.request<Components['schemas']['CaptureStreamingResultRead']>(requests.getResult(projectId, captureId, options)),
  };
}
