// Generated by apps/cert-prep-backend/scripts/generate_openapi_client.py.
// Source of truth: FastAPI OpenAPI schema from cert_prep_backend.api.app:create_app().
// Do not edit by hand.

export interface Components {
  schemas: {
    AnswerKeySource: string;
    Body_upload_document_projects__project_id__documents_post: { "file": string; "language_hint"?: string };
    ChunkList: { "items": Components['schemas']['ChunkRead'][] };
    ChunkRead: { "id": string; "document_id": string; "page_number": number; "chunk_index": number; "text": string; "raw_text": string; "line_start": number | null; "line_end": number | null; "line_count": number; "source_excerpt": string; "extraction_method": Components['schemas']['PdfExtractionMethod'] | string; "content_profile": Components['schemas']['ContentProfile'] | string; "created_at": string };
    ContentProfile: string;
    DocumentList: { "items": Components['schemas']['DocumentRead'][] };
    DocumentRead: { "id": string; "project_id": string; "filename": string; "sha256": string; "language_hint": string; "page_count": number; "has_text": boolean; "status": Components['schemas']['SourceDocumentStatus'] | string; "extraction_method": Components['schemas']['PdfExtractionMethod'] | string; "ocr_device": string | null; "ocr_fallback_reason": string | null; "ocr_duration_ms": number; "processed_page_count": number; "parse_wall_duration_ms": number; "render_duration_ms": number; "ocr_engine_duration_ms": number; "ocr_worker_count": number; "first_chunk_ms": number; "exam_item_count": number; "content_profile": Components['schemas']['ContentProfile'] | string; "classification_detail": string; "chunks_count": number; "created_at": string; "updated_at": string };
    DraftGenerateRequest: { "limit"?: number; "strategy"?: Components['schemas']['DraftGenerationStrategy'] };
    DraftGenerationJobList: { "items": Components['schemas']['DraftGenerationJobRead'][] };
    DraftGenerationJobRead: { "id": string; "project_id": string; "document_id": string; "chunk_id": string; "page_number": number; "strategy": Components['schemas']['DraftGenerationStrategy']; "status": string; "provider": string; "model": string; "generated_count": number; "retry_count": number; "last_error": string | null; "created_at": string; "updated_at": string };
    DraftGenerationStrategy: string;
    DraftStatus: string;
    HTTPValidationError: { "detail"?: Components['schemas']['ValidationError'][] };
    HealthResponse: { "status": string; "app": string; "version": string; "python_version": string; "runtime_mode": string };
    LLMHealthRead: { "provider": string; "model": string; "available": boolean; "detail": string; "unavailable_reason"?: string | null; "configured_model"?: string | null; "effective_model"?: string | null; "fallback_models"?: string[]; "fallback_reason"?: string | null; "profile_id"?: string | null; "base_model"?: string | null; "modelfile_sha256"?: string | null; "profile_reason"?: string | null; "profile_warnings"?: string[] };
    MachineAcceleratorRead: { "kind": string; "name": string; "vendor"?: string | null; "memory_bytes"?: number | null; "driver_version"?: string | null; "device_id"?: string | null };
    MachineCpuRead: { "architecture": string; "name"?: string | null; "physical_cores"?: number | null; "logical_cores"?: number | null };
    MachineInventoryRead: { "platform": string; "platform_version": string; "architecture": string; "cpu": Components['schemas']['MachineCpuRead']; "ram": Components['schemas']['MachineRamRead']; "storage": Components['schemas']['MachineStorageRead']; "accelerators"?: Components['schemas']['MachineAcceleratorRead'][]; "warnings"?: string[]; "schema_version"?: number };
    MachineRamRead: { "total_bytes"?: number | null; "available_bytes"?: number | null };
    MachineStorageRead: { "path": string; "free_bytes"?: number | null; "total_bytes"?: number | null };
    ModelDownloadRead: { "id": string; "provider": string; "model": string; "status": string; "detail": string; "completed": number | null; "total": number | null; "created_at": string; "updated_at": string; "error"?: string | null };
    OCRHealthRead: { "provider": string; "engine": string; "available": boolean; "detail": string; "python_version": string; "paddle_version": string | null; "paddleocr_version": string | null; "selected_device": string | null; "cuda_available": boolean; "gpu_count": number; "model_cache_dir": string | null; "fallback_reason": string | null; "unavailable_reason"?: string | null };
    OllamaModelProfileRead: { "profile_id": string; "display_name": string; "description": string; "base_model": string; "local_model": string; "context_window": number; "system_prompt": string; "parameters"?: Record<string, unknown>; "min_total_ram_bytes"?: number | null; "min_available_ram_bytes"?: number | null; "min_free_disk_bytes"?: number | null; "min_vram_bytes"?: number | null; "auto_selectable": boolean; "explicit_opt_in_required": boolean; "fallback_profile_ids"?: string[] };
    OllamaProfileSelectionRead: { "profile_enabled": boolean; "profile_id"?: string | null; "selected_profile"?: Components['schemas']['OllamaModelProfileRead'] | null; "support_status": string; "reason": string; "fallback_profiles"?: Components['schemas']['OllamaModelProfileRead'][]; "fallback_models"?: string[]; "warnings"?: string[]; "inventory"?: Components['schemas']['MachineInventoryRead'] | null; "modelfile_sha256"?: string | null; "effective_model": string; "base_model"?: string | null };
    OllamaProfilesRead: { "items": Components['schemas']['OllamaModelProfileRead'][] };
    PdfExtractionMethod: string;
    PracticeAttemptCreate: { "question_id": string; "selected_answer": string };
    PracticeAttemptRead: { "id": string; "session_id": string; "project_id": string; "question_id": string; "selected_answer": string; "is_correct": boolean; "created_at": string };
    PracticeSessionCreate: { "mode"?: Components['schemas']['PracticeSessionMode']; "document_id"?: string | null; "question_count"?: number | null; "random_seed"?: number | null };
    PracticeSessionMode: string;
    PracticeSessionRead: { "id": string; "project_id": string; "question_ids": string[]; "mode": Components['schemas']['PracticeSessionMode']; "document_id": string | null; "question_count": number; "random_seed": number | null; "status": string; "created_at": string; "completed_at": string | null };
    ProjectCreate: { "name": string; "description"?: string };
    ProjectList: { "items": Components['schemas']['ProjectRead'][] };
    ProjectRead: { "id": string; "name": string; "description": string; "created_at": string; "updated_at": string };
    ProjectUpdate: { "name"?: string | null; "description"?: string | null };
    QuestionDraftCreate: { "question"?: string; "choices"?: string[]; "answer"?: string | null; "answer_key_source"?: Components['schemas']['AnswerKeySource'] | string; "rationale"?: string | null; "citation_page"?: number | null; "source_excerpt"?: string | null; "confidence"?: number | null; "document_id"?: string | null; "chunk_id"?: string | null; "source_order"?: number | null; "source_question_number"?: string | null; "item_kind"?: Components['schemas']['QuestionItemKind'] | string; "group_key"?: string | null; "group_prompt"?: string | null };
    QuestionDraftList: { "items": Components['schemas']['QuestionDraftRead'][] };
    QuestionDraftRead: { "id": string; "project_id": string; "document_id": string | null; "chunk_id": string | null; "question": string; "choices": string[]; "answer": string | null; "answer_key_source": Components['schemas']['AnswerKeySource'] | string; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null; "confidence": number | null; "source_order": number | null; "source_question_number": string | null; "item_kind": Components['schemas']['QuestionItemKind'] | string; "group_key": string | null; "group_prompt": string | null; "status": Components['schemas']['DraftStatus'] | string; "rejection_reason": string | null; "created_at": string; "updated_at": string };
    QuestionDraftUpdate: { "question"?: string | null; "choices"?: string[] | null; "answer"?: string | null; "answer_key_source"?: Components['schemas']['AnswerKeySource'] | string | null; "rationale"?: string | null; "citation_page"?: number | null; "source_excerpt"?: string | null; "confidence"?: number | null; "source_order"?: number | null; "source_question_number"?: string | null; "item_kind"?: Components['schemas']['QuestionItemKind'] | string | null; "group_key"?: string | null; "group_prompt"?: string | null };
    QuestionItemKind: string;
    RuntimeInstallationRead: { "id": string; "kind": Components['schemas']['RuntimeRequirementKind']; "provider": string; "model": string; "status": Components['schemas']['RuntimeInstallationStatus']; "detail": string; "completed": number | null; "total": number | null; "created_at": string; "updated_at": string; "error"?: string | null };
    RuntimeInstallationStatus: string;
    RuntimeRequirementKind: string;
    RuntimeRequirementRead: { "kind": Components['schemas']['RuntimeRequirementKind']; "label": string; "available": boolean; "detail": string; "unavailable_reason": string | null; "version"?: string | null; "bytes"?: number | null; "installed_path"?: string | null };
    RuntimeRequirementsRead: { "items": Components['schemas']['RuntimeRequirementRead'][] };
    SourceDocumentStatus: string;
    ValidationError: { "loc": (string | number)[]; "msg": string; "type": string; "input"?: unknown; "ctx"?: Record<string, unknown> };
    WrongAnswerExplanationRead: { "attempt_id": string; "explanation": string; "provider": string; "model": string; "grounded_fields": Components['schemas']['WrongAnswerGroundedFields']; "fallback": boolean };
    WrongAnswerGroundedFields: { "question": string; "selected_answer": string; "correct_answer": string | null; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null };
    WrongAnswerList: { "items": Components['schemas']['WrongAnswerRead'][] };
    WrongAnswerRead: { "attempt_id": string; "session_id": string; "question_id": string; "question": string; "selected_answer": string; "correct_answer": string | null; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null; "created_at": string };
  };
}

export type AnswerKeySource = Components['schemas']['AnswerKeySource'];
export type Body_upload_document_projects__project_id__documents_post = Components['schemas']['Body_upload_document_projects__project_id__documents_post'];
export type ChunkList = Components['schemas']['ChunkList'];
export type ChunkRead = Components['schemas']['ChunkRead'];
export type ContentProfile = Components['schemas']['ContentProfile'];
export type DocumentList = Components['schemas']['DocumentList'];
export type DocumentRead = Components['schemas']['DocumentRead'];
export type DraftGenerateRequest = Components['schemas']['DraftGenerateRequest'];
export type DraftGenerationJobList = Components['schemas']['DraftGenerationJobList'];
export type DraftGenerationJobRead = Components['schemas']['DraftGenerationJobRead'];
export type DraftGenerationStrategy = Components['schemas']['DraftGenerationStrategy'];
export type DraftStatus = Components['schemas']['DraftStatus'];
export type HTTPValidationError = Components['schemas']['HTTPValidationError'];
export type HealthResponse = Components['schemas']['HealthResponse'];
export type LLMHealthRead = Components['schemas']['LLMHealthRead'];
export type MachineAcceleratorRead = Components['schemas']['MachineAcceleratorRead'];
export type MachineCpuRead = Components['schemas']['MachineCpuRead'];
export type MachineInventoryRead = Components['schemas']['MachineInventoryRead'];
export type MachineRamRead = Components['schemas']['MachineRamRead'];
export type MachineStorageRead = Components['schemas']['MachineStorageRead'];
export type ModelDownloadRead = Components['schemas']['ModelDownloadRead'];
export type OCRHealthRead = Components['schemas']['OCRHealthRead'];
export type OllamaModelProfileRead = Components['schemas']['OllamaModelProfileRead'];
export type OllamaProfileSelectionRead = Components['schemas']['OllamaProfileSelectionRead'];
export type OllamaProfilesRead = Components['schemas']['OllamaProfilesRead'];
export type PdfExtractionMethod = Components['schemas']['PdfExtractionMethod'];
export type PracticeAttemptCreate = Components['schemas']['PracticeAttemptCreate'];
export type PracticeAttemptRead = Components['schemas']['PracticeAttemptRead'];
export type PracticeSessionCreate = Components['schemas']['PracticeSessionCreate'];
export type PracticeSessionMode = Components['schemas']['PracticeSessionMode'];
export type PracticeSessionRead = Components['schemas']['PracticeSessionRead'];
export type ProjectCreate = Components['schemas']['ProjectCreate'];
export type ProjectList = Components['schemas']['ProjectList'];
export type ProjectRead = Components['schemas']['ProjectRead'];
export type ProjectUpdate = Components['schemas']['ProjectUpdate'];
export type QuestionDraftCreate = Components['schemas']['QuestionDraftCreate'];
export type QuestionDraftList = Components['schemas']['QuestionDraftList'];
export type QuestionDraftRead = Components['schemas']['QuestionDraftRead'];
export type QuestionDraftUpdate = Components['schemas']['QuestionDraftUpdate'];
export type QuestionItemKind = Components['schemas']['QuestionItemKind'];
export type RuntimeInstallationRead = Components['schemas']['RuntimeInstallationRead'];
export type RuntimeInstallationStatus = Components['schemas']['RuntimeInstallationStatus'];
export type RuntimeRequirementKind = Components['schemas']['RuntimeRequirementKind'];
export type RuntimeRequirementRead = Components['schemas']['RuntimeRequirementRead'];
export type RuntimeRequirementsRead = Components['schemas']['RuntimeRequirementsRead'];
export type SourceDocumentStatus = Components['schemas']['SourceDocumentStatus'];
export type ValidationError = Components['schemas']['ValidationError'];
export type WrongAnswerExplanationRead = Components['schemas']['WrongAnswerExplanationRead'];
export type WrongAnswerGroundedFields = Components['schemas']['WrongAnswerGroundedFields'];
export type WrongAnswerList = Components['schemas']['WrongAnswerList'];
export type WrongAnswerRead = Components['schemas']['WrongAnswerRead'];

export type CertPrepHttpMethod = 'DELETE' | 'GET' | 'PATCH' | 'POST';

export interface CertPrepHttpRequest {
  method: CertPrepHttpMethod;
  path: string;
  body?: unknown;
}

export interface CertPrepTransport {
  request<TResponse>(request: CertPrepHttpRequest): Promise<TResponse>;
}

export interface CertPrepGeneratedClient {
  health(): Promise<Components['schemas']['HealthResponse']>;
  listProjects(): Promise<Components['schemas']['ProjectList']>;
  createProject(body: Components['schemas']['ProjectCreate']): Promise<Components['schemas']['ProjectRead']>;
  getProject(projectId: string): Promise<Components['schemas']['ProjectRead']>;
  updateProject(projectId: string, body: Components['schemas']['ProjectUpdate']): Promise<Components['schemas']['ProjectRead']>;
  deleteProject(projectId: string): Promise<void>;
  listDocuments(projectId: string): Promise<Components['schemas']['DocumentList']>;
  uploadDocument(projectId: string, body: FormData): Promise<Components['schemas']['DocumentRead']>;
  getDocument(projectId: string, documentId: string): Promise<Components['schemas']['DocumentRead']>;
  listDocumentChunks(projectId: string, documentId: string): Promise<Components['schemas']['ChunkList']>;
  generateDocumentDrafts(projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest']): Promise<Components['schemas']['QuestionDraftList']>;
  listDocumentDraftJobs(projectId: string, documentId: string): Promise<Components['schemas']['DraftGenerationJobList']>;
  retryDocumentDraftJobs(projectId: string, documentId: string): Promise<Components['schemas']['DraftGenerationJobList']>;
  createQuestionDraft(projectId: string, body: Components['schemas']['QuestionDraftCreate']): Promise<Components['schemas']['QuestionDraftRead']>;
  listQuestionDrafts(projectId: string): Promise<Components['schemas']['QuestionDraftList']>;
  updateQuestionDraft(projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate']): Promise<Components['schemas']['QuestionDraftRead']>;
  createPracticeSession(projectId: string, body: Components['schemas']['PracticeSessionCreate']): Promise<Components['schemas']['PracticeSessionRead']>;
  getPracticeSession(projectId: string, sessionId: string): Promise<Components['schemas']['PracticeSessionRead']>;
  recordPracticeAttempt(projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate']): Promise<Components['schemas']['PracticeAttemptRead']>;
  listWrongAnswers(projectId: string): Promise<Components['schemas']['WrongAnswerList']>;
  explainWrongAnswer(projectId: string, attemptId: string): Promise<Components['schemas']['WrongAnswerExplanationRead']>;
  llmHealth(): Promise<Components['schemas']['LLMHealthRead']>;
  llmProfiles(): Promise<Components['schemas']['OllamaProfilesRead']>;
  llmProfileSelection(): Promise<Components['schemas']['OllamaProfileSelectionRead']>;
  startModelDownload(): Promise<Components['schemas']['ModelDownloadRead']>;
  getModelDownload(jobId: string): Promise<Components['schemas']['ModelDownloadRead']>;
  ocrHealth(): Promise<Components['schemas']['OCRHealthRead']>;
  runtimeRequirements(): Promise<Components['schemas']['RuntimeRequirementsRead']>;
  machineInventory(): Promise<Components['schemas']['MachineInventoryRead']>;
  startRuntimeInstallation(kind: string): Promise<Components['schemas']['RuntimeInstallationRead']>;
  getRuntimeInstallation(jobId: string): Promise<Components['schemas']['RuntimeInstallationRead']>;
}

export function createCertPrepGeneratedClient(
  transport: CertPrepTransport,
): CertPrepGeneratedClient {
  return {
    health: () =>
      transport.request<Components['schemas']['HealthResponse']>({ method: 'GET' as const, path: "/health" }),
    listProjects: () =>
      transport.request<Components['schemas']['ProjectList']>({ method: 'GET' as const, path: "/projects" }),
    createProject: (body: Components['schemas']['ProjectCreate']) =>
      transport.request<Components['schemas']['ProjectRead']>({ method: 'POST' as const, path: "/projects", body }),
    getProject: (projectId: string) =>
      transport.request<Components['schemas']['ProjectRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}` }),
    updateProject: (projectId: string, body: Components['schemas']['ProjectUpdate']) =>
      transport.request<Components['schemas']['ProjectRead']>({ method: 'PATCH' as const, path: `/projects/${encodeURIComponent(projectId)}`, body }),
    deleteProject: (projectId: string) =>
      transport.request<void>({ method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}` }),
    listDocuments: (projectId: string) =>
      transport.request<Components['schemas']['DocumentList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents` }),
    uploadDocument: (projectId: string, body: FormData) =>
      transport.request<Components['schemas']['DocumentRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents`, body }),
    getDocument: (projectId: string, documentId: string) =>
      transport.request<Components['schemas']['DocumentRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}` }),
    listDocumentChunks: (projectId: string, documentId: string) =>
      transport.request<Components['schemas']['ChunkList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/chunks` }),
    generateDocumentDrafts: (projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest']) =>
      transport.request<Components['schemas']['QuestionDraftList']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/drafts`, body }),
    listDocumentDraftJobs: (projectId: string, documentId: string) =>
      transport.request<Components['schemas']['DraftGenerationJobList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-jobs` }),
    retryDocumentDraftJobs: (projectId: string, documentId: string) =>
      transport.request<Components['schemas']['DraftGenerationJobList']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/draft-jobs/retry` }),
    createQuestionDraft: (projectId: string, body: Components['schemas']['QuestionDraftCreate']) =>
      transport.request<Components['schemas']['QuestionDraftRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts`, body }),
    listQuestionDrafts: (projectId: string) =>
      transport.request<Components['schemas']['QuestionDraftList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts` }),
    updateQuestionDraft: (projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate']) =>
      transport.request<Components['schemas']['QuestionDraftRead']>({ method: 'PATCH' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts/${encodeURIComponent(draftId)}`, body }),
    createPracticeSession: (projectId: string, body: Components['schemas']['PracticeSessionCreate']) =>
      transport.request<Components['schemas']['PracticeSessionRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions`, body }),
    getPracticeSession: (projectId: string, sessionId: string) =>
      transport.request<Components['schemas']['PracticeSessionRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}` }),
    recordPracticeAttempt: (projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate']) =>
      transport.request<Components['schemas']['PracticeAttemptRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}/attempts`, body }),
    listWrongAnswers: (projectId: string) =>
      transport.request<Components['schemas']['WrongAnswerList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/wrong-answers` }),
    explainWrongAnswer: (projectId: string, attemptId: string) =>
      transport.request<Components['schemas']['WrongAnswerExplanationRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/wrong-answers/${encodeURIComponent(attemptId)}/explanation` }),
    llmHealth: () =>
      transport.request<Components['schemas']['LLMHealthRead']>({ method: 'GET' as const, path: "/llm/health" }),
    llmProfiles: () =>
      transport.request<Components['schemas']['OllamaProfilesRead']>({ method: 'GET' as const, path: "/llm/profiles" }),
    llmProfileSelection: () =>
      transport.request<Components['schemas']['OllamaProfileSelectionRead']>({ method: 'GET' as const, path: "/llm/profile-selection" }),
    startModelDownload: () =>
      transport.request<Components['schemas']['ModelDownloadRead']>({ method: 'POST' as const, path: "/llm/model-downloads" }),
    getModelDownload: (jobId: string) =>
      transport.request<Components['schemas']['ModelDownloadRead']>({ method: 'GET' as const, path: `/llm/model-downloads/${encodeURIComponent(jobId)}` }),
    ocrHealth: () =>
      transport.request<Components['schemas']['OCRHealthRead']>({ method: 'GET' as const, path: "/ocr/health" }),
    runtimeRequirements: () =>
      transport.request<Components['schemas']['RuntimeRequirementsRead']>({ method: 'GET' as const, path: "/runtime/requirements" }),
    machineInventory: () =>
      transport.request<Components['schemas']['MachineInventoryRead']>({ method: 'GET' as const, path: "/runtime/machine-inventory" }),
    startRuntimeInstallation: (kind: string) =>
      transport.request<Components['schemas']['RuntimeInstallationRead']>({ method: 'POST' as const, path: `/runtime/installations/${encodeURIComponent(kind)}` }),
    getRuntimeInstallation: (jobId: string) =>
      transport.request<Components['schemas']['RuntimeInstallationRead']>({ method: 'GET' as const, path: `/runtime/installations/${encodeURIComponent(jobId)}` }),
  };
}
