"""Cert Prep host compatibility policy for the published Capture contracts."""

from capture_contracts import (
    CAPTURE_API_VERSION,
    CAPTURE_DOCUMENT_SCHEMA_VERSION as CONTRACT_SCHEMA_VERSION,
    CAPTURE_RUNTIME_VERSION,
)

CAPTURE_DOCUMENT_SCHEMA_VERSION = CONTRACT_SCHEMA_VERSION
SUPPORTED_API_VERSION = CAPTURE_API_VERSION
SUPPORTED_RUNTIME_VERSION = CAPTURE_RUNTIME_VERSION
SUPPORTED_API_MAJOR = int(SUPPORTED_API_VERSION.split(".", 1)[0])
SUPPORTED_RUNTIME_MAJOR = int(SUPPORTED_RUNTIME_VERSION.split(".", 1)[0])
SUPPORTED_RUNTIME_MINOR = int(SUPPORTED_RUNTIME_VERSION.split(".", 2)[1])
LEGACY_CORE_ONLY_RUNTIME_VERSION = "0.3.8"

__all__ = [
    "CAPTURE_DOCUMENT_SCHEMA_VERSION",
    "LEGACY_CORE_ONLY_RUNTIME_VERSION",
    "SUPPORTED_API_MAJOR",
    "SUPPORTED_API_VERSION",
    "SUPPORTED_RUNTIME_MAJOR",
    "SUPPORTED_RUNTIME_MINOR",
    "SUPPORTED_RUNTIME_VERSION",
]
