// Generated by apps/exam-prep-backend/scripts/generate_openapi_client.py.
// Source of truth: FastAPI OpenAPI schema from exam_prep_backend.app:create_app().
// Do not edit by hand.

export interface Components {
  schemas: {
    AnswerKeySource: string;
    Body_upload_document_projects__project_id__documents_post: { "file": string };
    ChunkList: { "items": Components['schemas']['ChunkRead'][] };
    ChunkRead: { "id": string; "document_id": string; "page_number": number; "chunk_index": number; "text": string; "source_excerpt": string; "extraction_method": Components['schemas']['PdfExtractionMethod'] | string; "created_at": string };
    DocumentRead: { "id": string; "project_id": string; "filename": string; "sha256": string; "page_count": number; "has_text": boolean; "status": Components['schemas']['SourceDocumentStatus'] | string; "extraction_method": Components['schemas']['PdfExtractionMethod'] | string; "ocr_device": string | null; "ocr_fallback_reason": string | null; "ocr_duration_ms": number; "processed_page_count": number; "exam_item_count": number; "chunks_count": number; "created_at": string };
    DraftGenerateRequest: { "limit"?: number };
    DraftStatus: string;
    HTTPValidationError: { "detail"?: Components['schemas']['ValidationError'][] };
    HealthResponse: { "status": string; "app": string; "version": string };
    LLMHealthRead: { "provider": string; "model": string; "available": boolean; "detail": string };
    OCRHealthRead: { "provider": string; "engine": string; "available": boolean; "detail": string; "python_version": string; "paddle_version": string | null; "paddleocr_version": string | null; "selected_device": string | null; "cuda_available": boolean; "gpu_count": number; "model_cache_dir": string | null; "fallback_reason": string | null };
    PdfExtractionMethod: string;
    PracticeAttemptCreate: { "question_id": string; "selected_answer": string };
    PracticeAttemptRead: { "id": string; "session_id": string; "project_id": string; "question_id": string; "selected_answer": string; "is_correct": boolean; "created_at": string };
    PracticeSessionCreate: { "question_count"?: number };
    PracticeSessionRead: { "id": string; "project_id": string; "question_ids": string[]; "status": string; "created_at": string; "completed_at": string | null };
    ProjectCreate: { "name": string; "description"?: string };
    ProjectList: { "items": Components['schemas']['ProjectRead'][] };
    ProjectRead: { "id": string; "name": string; "description": string; "created_at": string; "updated_at": string };
    ProjectUpdate: { "name"?: string | null; "description"?: string | null };
    QuestionDraftCreate: { "question"?: string; "choices"?: string[]; "answer"?: string | null; "answer_key_source"?: Components['schemas']['AnswerKeySource'] | string; "rationale"?: string | null; "citation_page"?: number | null; "source_excerpt"?: string | null; "document_id"?: string | null; "chunk_id"?: string | null };
    QuestionDraftList: { "items": Components['schemas']['QuestionDraftRead'][] };
    QuestionDraftRead: { "id": string; "project_id": string; "document_id": string | null; "chunk_id": string | null; "question": string; "choices": string[]; "answer": string | null; "answer_key_source": Components['schemas']['AnswerKeySource'] | string; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null; "status": Components['schemas']['DraftStatus'] | string; "rejection_reason": string | null; "created_at": string; "updated_at": string };
    QuestionDraftUpdate: { "question"?: string | null; "choices"?: string[] | null; "answer"?: string | null; "answer_key_source"?: Components['schemas']['AnswerKeySource'] | string | null; "rationale"?: string | null; "citation_page"?: number | null; "source_excerpt"?: string | null };
    SourceDocumentStatus: string;
    ValidationError: { "loc": (string | number)[]; "msg": string; "type": string; "input"?: unknown; "ctx"?: Record<string, unknown> };
    WrongAnswerList: { "items": Components['schemas']['WrongAnswerRead'][] };
    WrongAnswerRead: { "attempt_id": string; "session_id": string; "question_id": string; "question": string; "selected_answer": string; "correct_answer": string | null; "rationale": string | null; "citation_page": number | null; "source_excerpt": string | null; "created_at": string };
  };
}

export type AnswerKeySource = Components['schemas']['AnswerKeySource'];
export type Body_upload_document_projects__project_id__documents_post = Components['schemas']['Body_upload_document_projects__project_id__documents_post'];
export type ChunkList = Components['schemas']['ChunkList'];
export type ChunkRead = Components['schemas']['ChunkRead'];
export type DocumentRead = Components['schemas']['DocumentRead'];
export type DraftGenerateRequest = Components['schemas']['DraftGenerateRequest'];
export type DraftStatus = Components['schemas']['DraftStatus'];
export type HTTPValidationError = Components['schemas']['HTTPValidationError'];
export type HealthResponse = Components['schemas']['HealthResponse'];
export type LLMHealthRead = Components['schemas']['LLMHealthRead'];
export type OCRHealthRead = Components['schemas']['OCRHealthRead'];
export type PdfExtractionMethod = Components['schemas']['PdfExtractionMethod'];
export type PracticeAttemptCreate = Components['schemas']['PracticeAttemptCreate'];
export type PracticeAttemptRead = Components['schemas']['PracticeAttemptRead'];
export type PracticeSessionCreate = Components['schemas']['PracticeSessionCreate'];
export type PracticeSessionRead = Components['schemas']['PracticeSessionRead'];
export type ProjectCreate = Components['schemas']['ProjectCreate'];
export type ProjectList = Components['schemas']['ProjectList'];
export type ProjectRead = Components['schemas']['ProjectRead'];
export type ProjectUpdate = Components['schemas']['ProjectUpdate'];
export type QuestionDraftCreate = Components['schemas']['QuestionDraftCreate'];
export type QuestionDraftList = Components['schemas']['QuestionDraftList'];
export type QuestionDraftRead = Components['schemas']['QuestionDraftRead'];
export type QuestionDraftUpdate = Components['schemas']['QuestionDraftUpdate'];
export type SourceDocumentStatus = Components['schemas']['SourceDocumentStatus'];
export type ValidationError = Components['schemas']['ValidationError'];
export type WrongAnswerList = Components['schemas']['WrongAnswerList'];
export type WrongAnswerRead = Components['schemas']['WrongAnswerRead'];

export type ExamPrepHttpMethod = 'DELETE' | 'GET' | 'PATCH' | 'POST';

export interface ExamPrepHttpRequest {
  method: ExamPrepHttpMethod;
  path: string;
  body?: unknown;
}

export interface ExamPrepTransport {
  request<TResponse>(request: ExamPrepHttpRequest): Promise<TResponse>;
}

export interface ExamPrepGeneratedClient {
  health(): Promise<Components['schemas']['HealthResponse']>;
  listProjects(): Promise<Components['schemas']['ProjectList']>;
  createProject(body: Components['schemas']['ProjectCreate']): Promise<Components['schemas']['ProjectRead']>;
  getProject(projectId: string): Promise<Components['schemas']['ProjectRead']>;
  updateProject(projectId: string, body: Components['schemas']['ProjectUpdate']): Promise<Components['schemas']['ProjectRead']>;
  deleteProject(projectId: string): Promise<void>;
  uploadDocument(projectId: string, body: FormData): Promise<Components['schemas']['DocumentRead']>;
  listDocumentChunks(projectId: string, documentId: string): Promise<Components['schemas']['ChunkList']>;
  generateDocumentDrafts(projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest']): Promise<Components['schemas']['QuestionDraftList']>;
  createQuestionDraft(projectId: string, body: Components['schemas']['QuestionDraftCreate']): Promise<Components['schemas']['QuestionDraftRead']>;
  listQuestionDrafts(projectId: string): Promise<Components['schemas']['QuestionDraftList']>;
  updateQuestionDraft(projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate']): Promise<Components['schemas']['QuestionDraftRead']>;
  approveQuestionDraft(projectId: string, draftId: string): Promise<Components['schemas']['QuestionDraftRead']>;
  createPracticeSession(projectId: string, body: Components['schemas']['PracticeSessionCreate']): Promise<Components['schemas']['PracticeSessionRead']>;
  getPracticeSession(projectId: string, sessionId: string): Promise<Components['schemas']['PracticeSessionRead']>;
  recordPracticeAttempt(projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate']): Promise<Components['schemas']['PracticeAttemptRead']>;
  listWrongAnswers(projectId: string): Promise<Components['schemas']['WrongAnswerList']>;
  llmHealth(): Promise<Components['schemas']['LLMHealthRead']>;
  ocrHealth(): Promise<Components['schemas']['OCRHealthRead']>;
}

export function createExamPrepGeneratedClient(
  transport: ExamPrepTransport,
): ExamPrepGeneratedClient {
  return {
    health: () =>
      transport.request<Components['schemas']['HealthResponse']>({ method: 'GET' as const, path: "/health" }),
    listProjects: () =>
      transport.request<Components['schemas']['ProjectList']>({ method: 'GET' as const, path: "/projects" }),
    createProject: (body: Components['schemas']['ProjectCreate']) =>
      transport.request<Components['schemas']['ProjectRead']>({ method: 'POST' as const, path: "/projects", body }),
    getProject: (projectId: string) =>
      transport.request<Components['schemas']['ProjectRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}` }),
    updateProject: (projectId: string, body: Components['schemas']['ProjectUpdate']) =>
      transport.request<Components['schemas']['ProjectRead']>({ method: 'PATCH' as const, path: `/projects/${encodeURIComponent(projectId)}`, body }),
    deleteProject: (projectId: string) =>
      transport.request<void>({ method: 'DELETE' as const, path: `/projects/${encodeURIComponent(projectId)}` }),
    uploadDocument: (projectId: string, body: FormData) =>
      transport.request<Components['schemas']['DocumentRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents`, body }),
    listDocumentChunks: (projectId: string, documentId: string) =>
      transport.request<Components['schemas']['ChunkList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/chunks` }),
    generateDocumentDrafts: (projectId: string, documentId: string, body: Components['schemas']['DraftGenerateRequest']) =>
      transport.request<Components['schemas']['QuestionDraftList']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}/drafts`, body }),
    createQuestionDraft: (projectId: string, body: Components['schemas']['QuestionDraftCreate']) =>
      transport.request<Components['schemas']['QuestionDraftRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts`, body }),
    listQuestionDrafts: (projectId: string) =>
      transport.request<Components['schemas']['QuestionDraftList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts` }),
    updateQuestionDraft: (projectId: string, draftId: string, body: Components['schemas']['QuestionDraftUpdate']) =>
      transport.request<Components['schemas']['QuestionDraftRead']>({ method: 'PATCH' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts/${encodeURIComponent(draftId)}`, body }),
    approveQuestionDraft: (projectId: string, draftId: string) =>
      transport.request<Components['schemas']['QuestionDraftRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/question-drafts/${encodeURIComponent(draftId)}/approve` }),
    createPracticeSession: (projectId: string, body: Components['schemas']['PracticeSessionCreate']) =>
      transport.request<Components['schemas']['PracticeSessionRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions`, body }),
    getPracticeSession: (projectId: string, sessionId: string) =>
      transport.request<Components['schemas']['PracticeSessionRead']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}` }),
    recordPracticeAttempt: (projectId: string, sessionId: string, body: Components['schemas']['PracticeAttemptCreate']) =>
      transport.request<Components['schemas']['PracticeAttemptRead']>({ method: 'POST' as const, path: `/projects/${encodeURIComponent(projectId)}/practice-sessions/${encodeURIComponent(sessionId)}/attempts`, body }),
    listWrongAnswers: (projectId: string) =>
      transport.request<Components['schemas']['WrongAnswerList']>({ method: 'GET' as const, path: `/projects/${encodeURIComponent(projectId)}/wrong-answers` }),
    llmHealth: () =>
      transport.request<Components['schemas']['LLMHealthRead']>({ method: 'GET' as const, path: "/llm/health" }),
    ocrHealth: () =>
      transport.request<Components['schemas']['OCRHealthRead']>({ method: 'GET' as const, path: "/ocr/health" }),
  };
}
